# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing

__all__ = [
    "RAGFSBindingClient",
    "reopen_tracing_file",
]

@typing.final
class RAGFSBindingClient:
    r"""
    RAGFS Python Binding Client.

    Embeds the ragfs filesystem engine directly in the Python process.
    API-compatible with the Go-based AGFSBindingClient.
    """
    def __new__(
        cls,
        config_path: typing.Optional[builtins.str] = None,
        config: typing.Optional[typing.Mapping[builtins.str, typing.Any]] = None,
        git_config_path: typing.Optional[builtins.str] = None,
    ) -> RAGFSBindingClient:
        r"""
        Create a new RAGFS binding client.

        `config_path` loads the canonical ov.conf schema. Removed cache schemas are rejected.
        `config` is an optional sectioned dict produced by the Python runtime. The `encryption`
        section, when present, carries `root_key` (32 bytes) + `provider_type` (int) and causes the
        stack to include an `EncryptionWrappedFS` layer. Runtime `cache` configuration takes
        precedence over `config_path`.
        """
    def close(self) -> None:
        r"""
        Stop mounted background services, then close the shared CacheRuntime.
        """
    def health(self) -> builtins.dict[builtins.str, builtins.str]:
        r"""
        Check client health.
        """
    def git_commit(self, **kwargs: typing.Any) -> typing.Any:
        r"""
        Commit a snapshot of the account's tree.
        """
    def git_restore(self, **kwargs: typing.Any) -> typing.Any:
        r"""
        Restore a project_dir subtree to the state at source_commit.
        """
    def git_show(self, **kwargs: typing.Any) -> typing.Any:
        r"""
        Read a commit's metadata or a blob's bytes at a path.
        """
    def git_diff_text(self, **kwargs: typing.Any) -> builtins.str:
        r"""
        Build a bounded unified text diff outside the Python interpreter.
        """
    def git_log(self, **kwargs: typing.Any) -> typing.Any:
        r"""
        Walk snapshot history, optionally filtered to commits touching paths.
        """
    def get_capabilities(self) -> builtins.dict[builtins.str, typing.Any]:
        r"""
        Get client capabilities.
        """
    def ls(
        self,
        path: builtins.str,
        ctx: typing.Optional[typing.Mapping[builtins.str, builtins.str]] = None,
        *,
        offset: builtins.int = 0,
        limit: typing.Optional[builtins.int] = None,
        sort_by: typing.Optional[builtins.str] = None,
        sort_order: typing.Optional[builtins.str] = None,
    ) -> typing.Any:
        r"""
        List directory contents.

        Returns a list of file info dicts with keys:
        name, size, mode, modTime, isDir
        """
    def read(
        self,
        path: builtins.str,
        offset: builtins.int = 0,
        size: builtins.int = -1,
        stream: builtins.bool = False,
        ctx: typing.Optional[typing.Mapping[builtins.str, builtins.str]] = None,
    ) -> typing.Any:
        r"""
        Read file content.

        Args:
            path: File path
            offset: Starting position (default: 0)
            size: Number of bytes to read (default: -1, read all)
            stream: Not supported in binding mode
            ctx: Optional FsContext dict (e.g. {"account_id": ...})
        """
    def cat(
        self,
        path: builtins.str,
        offset: builtins.int = 0,
        size: builtins.int = -1,
        stream: builtins.bool = False,
        ctx: typing.Optional[typing.Mapping[builtins.str, builtins.str]] = None,
    ) -> typing.Any:
        r"""
        Read file content (alias for read).
        """
    def write(
        self,
        path: builtins.str,
        data: typing.Sequence[builtins.int],
        max_retries: builtins.int = 3,
        ctx: typing.Optional[typing.Mapping[builtins.str, builtins.str]] = None,
    ) -> builtins.str:
        r"""
        Write data to file.

        Args:
            path: File path
            data: File content as bytes
            ctx: Optional FsContext dict (e.g. {"account_id": ...})
        """
    def create(
        self,
        path: builtins.str,
        ctx: typing.Optional[typing.Mapping[builtins.str, builtins.str]] = None,
    ) -> builtins.dict[builtins.str, builtins.str]:
        r"""
        Create a new empty file.
        """
    def mkdir(
        self,
        path: builtins.str,
        mode: builtins.str = "755",
        ctx: typing.Optional[typing.Mapping[builtins.str, builtins.str]] = None,
    ) -> builtins.dict[builtins.str, builtins.str]:
        r"""
        Create a directory.
        """
    def ensure_parent_dirs(
        self,
        path: builtins.str,
        mode: builtins.str = "755",
        ctx: typing.Optional[typing.Mapping[builtins.str, builtins.str]] = None,
    ) -> builtins.dict[builtins.str, builtins.str]:
        r"""
        Ensure all parent directories exist for the given path.
        """
    def rm(
        self,
        path: builtins.str,
        recursive: builtins.bool = False,
        ctx: typing.Optional[typing.Mapping[builtins.str, builtins.str]] = None,
    ) -> builtins.dict[builtins.str, builtins.str]:
        r"""
        Remove a file or directory.
        """
    def stat(
        self,
        path: builtins.str,
        ctx: typing.Optional[typing.Mapping[builtins.str, builtins.str]] = None,
    ) -> typing.Any:
        r"""
        Get file/directory information.
        """
    def mv(
        self,
        old_path: builtins.str,
        new_path: builtins.str,
        ctx: typing.Optional[typing.Mapping[builtins.str, builtins.str]] = None,
    ) -> builtins.dict[builtins.str, builtins.str]:
        r"""
        Rename/move a file or directory.
        """
    def copy_within_mount(
        self,
        src_path: builtins.str,
        dst_path: builtins.str,
        ctx: typing.Optional[typing.Mapping[builtins.str, builtins.str]] = None,
    ) -> builtins.dict[builtins.str, builtins.bool]:
        r"""
        Attempt a same-mount verbatim copy and report whether the fast-path was used.
        """
    def chmod(
        self,
        path: builtins.str,
        mode: builtins.int,
        ctx: typing.Optional[typing.Mapping[builtins.str, builtins.str]] = None,
    ) -> builtins.dict[builtins.str, builtins.str]:
        r"""
        Change file permissions.
        """
    def touch(
        self,
        path: builtins.str,
        ctx: typing.Optional[typing.Mapping[builtins.str, builtins.str]] = None,
    ) -> builtins.dict[builtins.str, builtins.str]:
        r"""
        Touch a file (create if not exists, or update timestamp).
        """
    def mounts(self) -> builtins.list[builtins.dict[builtins.str, builtins.str]]:
        r"""
        List all mounted plugins.
        """
    def mount(
        self, fstype: builtins.str, path: builtins.str, config: typing.Optional[dict] = None
    ) -> builtins.dict[builtins.str, builtins.str]:
        r"""
        Mount a plugin dynamically.

        Args:
            fstype: Filesystem type (e.g., "memfs", "sqlfs", "kvfs", "queuefs")
            path: Mount path
            config: Plugin configuration as dict. For multi-write, include:
                - "backups": nested dict matching BackendsConfig schema
                - "server_encryption_enabled": bool
                - "primary_encryption_enabled": bool
                - "primary_redirects": list of redirect policy dicts
        """
    def unmount(self, path: builtins.str) -> builtins.dict[builtins.str, builtins.str]:
        r"""
        Unmount a plugin.
        """
    def list_plugins(self) -> builtins.list[builtins.str]:
        r"""
        List all registered plugin names.
        """
    def get_plugins_info(self) -> builtins.list[builtins.str]:
        r"""
        Get detailed plugin information.
        """
    def load_plugin(self, _library_path: builtins.str) -> builtins.dict[builtins.str, builtins.str]:
        r"""
        Load an external plugin (not supported in Rust binding).
        """
    def unload_plugin(
        self, _library_path: builtins.str
    ) -> builtins.dict[builtins.str, builtins.str]:
        r"""
        Unload an external plugin (not supported in Rust binding).
        """
    def grep(
        self,
        path: builtins.str,
        pattern: builtins.str,
        recursive: builtins.bool = False,
        case_insensitive: builtins.bool = False,
        stream: builtins.bool = False,
        node_limit: typing.Optional[builtins.int] = None,
        exclude_path: typing.Optional[builtins.str] = None,
        level_limit: typing.Optional[builtins.int] = None,
        ctx: typing.Optional[typing.Mapping[builtins.str, builtins.str]] = None,
    ) -> typing.Any:
        r"""
        Search for pattern in files using regular expressions.

        Args:
            path: File or directory path to search
            pattern: Regular expression pattern to search for
            recursive: Whether to search recursively in subdirectories (default: false)
            case_insensitive: Whether to perform case-insensitive matching (default: false)
            stream: Not supported in binding mode
            node_limit: Maximum number of matches to return (default: None, no limit)
            exclude_path: Optional path prefix to exclude from search (default: None)
            level_limit: Optional maximum depth relative to query root (default: None)
            ctx: Optional FsContext dict (e.g. {"account_id": ...})

        Returns:
            A dict with "matches" (list of match dicts) and "count" (total matches)
        """
    def tree_directory(
        self,
        path: builtins.str,
        show_hidden: builtins.bool = False,
        node_limit: typing.Optional[builtins.int] = None,
        level_limit: typing.Optional[builtins.int] = None,
        ctx: typing.Optional[typing.Mapping[builtins.str, builtins.str]] = None,
        *,
        offset: builtins.int = 0,
        sort_by: typing.Optional[builtins.str] = None,
        sort_order: typing.Optional[builtins.str] = None,
    ) -> typing.Any:
        r"""
        Recursively traverse a directory tree.

        Args:
            path: The root path of the traversal
            show_hidden: Whether to include hidden files (default: False)
            node_limit: Maximum number of nodes to return (default: None, no limit)
            level_limit: Maximum depth relative to query root (default: None, no limit)
            ctx: Optional FsContext dict (e.g. {"account_id": ...})

        Returns:
            A list of dicts, each with keys: path, rel_path, info, extra
        """
    def glob_directory(
        self,
        path: builtins.str,
        pattern: builtins.str,
        show_hidden: builtins.bool = False,
        page_size: typing.Optional[builtins.int] = None,
        level_limit: typing.Optional[builtins.int] = None,
        continuation_token: typing.Optional[builtins.str] = None,
        ctx: typing.Optional[typing.Mapping[builtins.str, builtins.str]] = None,
    ) -> typing.Any:
        r"""
        Return one page of flat glob results.

        Args:
            path: The root path of the traversal
            pattern: Glob pattern matched against query-root-relative paths
            show_hidden: Whether to include hidden files (default: False)
            page_size: Maximum number of matched entries returned in this page
            level_limit: Maximum depth relative to query root (default: None)
            continuation_token: Opaque token returned by the previous page
            ctx: Optional FsContext dict (e.g. {"account_id": ...})

        Returns:
            A dict with keys: entries (list[GlobEntry]), next_token (str | None)
        """
    def system_sync_status(
        self,
        path: builtins.str,
        ctx: typing.Optional[typing.Mapping[builtins.str, builtins.str]] = None,
    ) -> typing.Any:
        r"""
        Query multi-write sync status under a file or directory path.

        Args:
            path: Absolute AGFS path rooted at the mounted namespace
            ctx: Optional FsContext dict (e.g. {"account_id": ...})

        Returns:
            A JSON-like dict describing pending and acknowledged backup sync state.
        """
    def system_sync_retry(
        self,
        path: builtins.str,
        ctx: typing.Optional[typing.Mapping[builtins.str, builtins.str]] = None,
    ) -> typing.Any:
        r"""
        Manually retry lagging multi-write backup sync operations under a path.

        Args:
            path: Absolute AGFS path rooted at the mounted namespace
            ctx: Optional FsContext dict (e.g. {"account_id": ...})

        Returns:
            A JSON-like dict summarizing retry results per target backend.
        """
    def digest(
        self, path: builtins.str, algorithm: builtins.str = "xxh3"
    ) -> builtins.dict[builtins.str, builtins.str]:
        r"""
        Calculate file digest (not yet implemented in ragfs).
        """
    def pathlock_acquire_exact(
        self,
        ctx: typing.Optional[typing.Mapping[builtins.str, builtins.str]],
        path: builtins.str,
        timeout_secs: builtins.float = 0.0,
        owner_lease_ref: typing.Optional[typing.Any] = None,
    ) -> typing.Any:
        r"""
        Acquire an exact lock on a single path.
        """
    def pathlock_acquire_exact_batch(
        self,
        ctx: typing.Optional[typing.Mapping[builtins.str, builtins.str]],
        paths: typing.Sequence[builtins.str],
        timeout_secs: builtins.float = 0.0,
        owner_lease_ref: typing.Optional[typing.Any] = None,
    ) -> typing.Any:
        r"""
        Acquire exact locks on multiple paths.
        """
    def pathlock_acquire_tree(
        self,
        ctx: typing.Optional[typing.Mapping[builtins.str, builtins.str]],
        path: builtins.str,
        timeout_secs: builtins.float = 0.0,
        owner_lease_ref: typing.Optional[typing.Any] = None,
    ) -> typing.Any:
        r"""
        Acquire a tree lock on a single path.
        """
    def pathlock_acquire_tree_batch(
        self,
        ctx: typing.Optional[typing.Mapping[builtins.str, builtins.str]],
        paths: typing.Sequence[builtins.str],
        timeout_secs: builtins.float = 0.0,
        owner_lease_ref: typing.Optional[typing.Any] = None,
    ) -> typing.Any:
        r"""
        Acquire tree locks on multiple paths.
        """
    def pathlock_acquire_exact_tree_batch(
        self,
        ctx: typing.Optional[typing.Mapping[builtins.str, builtins.str]],
        exact_paths: typing.Sequence[builtins.str],
        tree_paths: typing.Sequence[builtins.str],
        timeout_secs: builtins.float = 0.0,
        owner_lease_ref: typing.Optional[typing.Any] = None,
    ) -> typing.Any:
        r"""
        Acquire a mixed batch of exact and tree locks.
        """
    def pathlock_acquire_batch(
        self,
        ctx: typing.Optional[typing.Mapping[builtins.str, builtins.str]],
        requests: typing.Sequence[typing.Mapping[builtins.str, builtins.str]],
        timeout_secs: builtins.float = 0.0,
        owner_lease_ref: typing.Optional[typing.Any] = None,
    ) -> typing.Any:
        r"""
        Acquire a batch of locks from a list of request dicts.
        Each request dict: {"path": str, "kind": "exact"|"tree"}
        """
    def pathlock_as_borrowed(
        self,
        ctx: typing.Optional[typing.Mapping[builtins.str, builtins.str]],
        owned_lease_ref: typing.Any,
    ) -> typing.Any:
        r"""
        Create a borrowed view of an owned lease.
        """
    def pathlock_refresh(
        self,
        ctx: typing.Optional[typing.Mapping[builtins.str, builtins.str]],
        owned_lease_ref: typing.Any,
    ) -> builtins.str:
        r"""
        Refresh an owned lease. Returns "refreshed", "lost", or "failed".
        """
    def pathlock_release(
        self,
        ctx: typing.Optional[typing.Mapping[builtins.str, builtins.str]],
        owned_lease_ref: typing.Any,
    ) -> None:
        r"""
        Release an owned lease.
        """
    def pathlock_release_selected(
        self,
        ctx: typing.Optional[typing.Mapping[builtins.str, builtins.str]],
        owned_lease_ref: typing.Any,
        lock_paths: typing.Sequence[builtins.str],
    ) -> None:
        r"""
        Release selected lock paths from an owned lease.
        """
    def pathlock_to_handoff(
        self,
        ctx: typing.Optional[typing.Mapping[builtins.str, builtins.str]],
        owned_lease_ref: typing.Any,
    ) -> typing.Any:
        r"""
        Export a handoff ref from an owned lease.
        """
    def pathlock_handoff(
        self,
        ctx: typing.Optional[typing.Mapping[builtins.str, builtins.str]],
        owned_lease_ref: typing.Any,
    ) -> None:
        r"""
        Mark an owned lease as handed off.
        """
    def pathlock_adopt(
        self,
        ctx: typing.Optional[typing.Mapping[builtins.str, builtins.str]],
        handoff_ref: typing.Mapping[builtins.str, typing.Any],
    ) -> typing.Any:
        r"""
        Adopt a handoff ref, returning a new owned lease.
        """
    def pathlock_is_locked(
        self,
        ctx: typing.Optional[typing.Mapping[builtins.str, builtins.str]],
        path: builtins.str,
        ignore_stale: builtins.bool = True,
    ) -> builtins.bool:
        r"""
        Check if a path is locked.
        """
    def pathlock_observe(
        self, ctx: typing.Optional[typing.Mapping[builtins.str, builtins.str]] = None
    ) -> typing.Any:
        r"""
        Return an observability snapshot of current lock state.
        """
    def metrics(self) -> list:
        r"""
        Read all native metrics with no arguments and return a list of flat Python dicts.
        """
    def get_stats(self, path: typing.Optional[builtins.str] = None) -> typing.Any:
        r"""
        Get filesystem statistics.

        Args:
            path: Optional mount path to get stats for. If None, get stats for all mounts.

        Returns:
            Statistics data as a dict.
        """

def reopen_tracing_file() -> None:
    r"""
    Reopen the Rust tracing log file after Python rotates the active log file.
    """
