#!/usr/bin/env python3
"""Backfill historical context-commit stats for the Studio usage heatmap.

The ``usage_context_write_bucket`` table only records ``add_resource`` /
``add_skill`` / ``session_add_message`` / ``session_commit`` events emitted
after the Usage/Audit system was enabled, so resources ingested earlier never
show up in the Studio "context commits" heatmap. This one-off maintenance
script approximates the missing history by counting one ``add_resource`` per
top-level entry under the workspace resources directory -- matching the live
metric's unit of one successful ``POST /api/v1/resources`` request -- and
bucketing each entry's earliest content-file mtime into 4-hour UTC buckets in
the ``usage_context_write_bucket`` table.

Generated semantic sidecars (``.abstract.md`` / ``.overview.md`` /
``.relations.json``) never count and never contribute timestamps. Entries
ingested after the live recorder started (derived from the earliest
``request_audit`` row, which this script never writes) are skipped so live
request counts are not double counted.

Usage:
    python scripts/maintenance/usage_context_write_backfill/backfill_context_writes.py \
        --workspace /path/to/workspace --account default --user default

Limitations:
    - Only ``add_resource`` is backfilled; the other operations leave no
      per-file timestamp to recover.
    - File mtime may differ from the original ingestion time after copies or
      migrations.
    - One request importing into the resources root can expand into several
      top-level entries, so backfilled counts remain an approximation of the
      request count.
"""

from __future__ import annotations

import argparse
import os
import sqlite3
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path

BUCKET_HOURS = 4

# Generated by the semantic pipeline after ingestion; excluded from both
# counting and ingestion-time estimation (their mtimes are always later).
SIDECAR_FILENAMES = {".abstract.md", ".overview.md", ".relations.json"}

UPSERT_SQL = """
INSERT INTO usage_context_write_bucket
    (account_id, user_id, date_utc, hour_utc, operation, count, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(account_id, user_id, date_utc, hour_utc, operation)
DO UPDATE SET count = count + excluded.count, updated_at = excluded.updated_at
"""


def _entry_ingestion_time(entry: Path) -> datetime | None:
    """Earliest content-file mtime within a top-level resource entry.

    The earliest file of an import is closest to the original request time;
    sidecars are generated later and are ignored.
    """
    earliest: float | None = None
    if entry.is_file():
        try:
            earliest = entry.stat().st_mtime
        except OSError:
            return None
    else:
        for root, _dirs, fnames in os.walk(entry):
            for fname in fnames:
                if fname in SIDECAR_FILENAMES:
                    continue
                try:
                    mtime = (Path(root) / fname).stat().st_mtime
                except OSError:
                    continue
                if earliest is None or mtime < earliest:
                    earliest = mtime
    if earliest is None:
        return None
    return datetime.fromtimestamp(earliest, tz=timezone.utc)


def scan_resource_entries(resources_dir: Path, cutoff: datetime | None = None) -> Counter:
    """Count one add_resource per top-level entry, bucketed by ingestion time.

    Matches the live metric's unit (one count per successful add_resource
    request); entries ingested at or after ``cutoff`` are skipped because the
    live recorder already counted them.
    """
    buckets: Counter = Counter()
    if not resources_dir.is_dir():
        return buckets
    for entry in sorted(resources_dir.iterdir()):
        if entry.name in SIDECAR_FILENAMES:
            continue
        ingested_at = _entry_ingestion_time(entry)
        if ingested_at is None:
            continue
        if cutoff is not None and ingested_at >= cutoff:
            continue
        date_utc = ingested_at.strftime("%Y-%m-%d")
        hour_utc = (ingested_at.hour // BUCKET_HOURS) * BUCKET_HOURS
        buckets[(date_utc, hour_utc)] += 1
    return buckets


def recorder_start_time(db_path: Path) -> datetime | None:
    """Earliest ``request_audit`` row, marking when the live recorder started.

    The backfill never writes ``request_audit``, so this cutoff stays valid
    even after a previous backfill run polluted ``usage_context_write_bucket``
    with historical dates.
    """
    conn = sqlite3.connect(str(db_path))
    try:
        table_exists = conn.execute(
            "SELECT name FROM sqlite_master WHERE type='table' AND name='request_audit'"
        ).fetchone()
        if table_exists is None:
            return None
        row = conn.execute("SELECT MIN(created_at) FROM request_audit").fetchone()
    finally:
        conn.close()
    if not row or not row[0]:
        return None
    try:
        started = datetime.fromisoformat(str(row[0]))
    except ValueError:
        return None
    if started.tzinfo is None:
        started = started.replace(tzinfo=timezone.utc)
    return started.astimezone(timezone.utc)


def backfill(db_path: Path, buckets: Counter, account_id: str, user_id: str) -> int:
    """Upsert aggregated buckets into ``usage_context_write_bucket``."""
    conn = sqlite3.connect(str(db_path))
    try:
        cursor = conn.cursor()
        table_exists = cursor.execute(
            "SELECT name FROM sqlite_master WHERE type='table' AND name='usage_context_write_bucket'"
        ).fetchone()
        if table_exists is None:
            raise RuntimeError(
                "Table usage_context_write_bucket does not exist. "
                "Start the server once with Usage/Audit enabled to create the schema."
            )
        now = datetime.now(timezone.utc).isoformat()
        inserted = 0
        for (date_utc, hour_utc), count in sorted(buckets.items()):
            cursor.execute(
                UPSERT_SQL,
                (account_id, user_id, date_utc, hour_utc, "add_resource", count, now),
            )
            inserted += cursor.rowcount
        conn.commit()
        return inserted
    finally:
        conn.close()


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Backfill historical context-commit stats from resource entry mtimes."
    )
    parser.add_argument(
        "--workspace",
        type=Path,
        required=True,
        help="OpenViking workspace path (the directory holding viking/ and _system/)",
    )
    parser.add_argument("--account", default="default", help="account_id to attribute rows to")
    parser.add_argument("--user", default="default", help="user_id to attribute rows to")
    parser.add_argument(
        "--resources-dir",
        type=Path,
        default=None,
        help="Override the resources directory (default: <workspace>/viking/<account>/resources)",
    )
    parser.add_argument(
        "--cutoff",
        default=None,
        help=(
            "ISO-8601 timestamp; entries ingested at or after it are skipped "
            "(default: earliest request_audit row, i.e. when the live recorder started)"
        ),
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Scan and report bucket counts without writing to the database",
    )
    args = parser.parse_args()

    resources_dir = args.resources_dir or (args.workspace / "viking" / args.account / "resources")
    db_path = args.workspace / "_system" / "usage_audit" / "usage_audit.sqlite3"

    if not db_path.exists():
        print(f"Error: Usage/Audit database not found: {db_path}")
        print("Start the server once with Usage/Audit enabled, then re-run this script.")
        return 1

    cutoff: datetime | None
    if args.cutoff:
        cutoff = datetime.fromisoformat(args.cutoff)
        if cutoff.tzinfo is None:
            cutoff = cutoff.replace(tzinfo=timezone.utc)
    else:
        cutoff = recorder_start_time(db_path)
    if cutoff is not None:
        print(f"Skipping entries ingested at or after {cutoff.isoformat()} (recorded live)")
    else:
        print("No live recorder history found; backfilling all entries")

    buckets = scan_resource_entries(resources_dir, cutoff=cutoff)
    total_entries = sum(buckets.values())
    print(f"Found {total_entries} top-level resource entries across {len(buckets)} time buckets")

    if total_entries == 0:
        print("No backfillable resource entries found; nothing to do.")
        return 0

    if args.dry_run:
        for (date_utc, hour_utc), count in sorted(buckets.items()):
            print(f"  {date_utc} {hour_utc:02d}:00 UTC  add_resource x{count}")
        print("Dry run: no rows written.")
        return 0

    inserted = backfill(db_path, buckets, args.account, args.user)
    print(f"Backfilled {inserted} rows into usage_context_write_bucket")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
