/**
 * Config-driven skillset visibility filtering for the retrieval surfaces.
 *
 * Two orthogonal knobs, each an array of set names (file config or the env
 * equivalents, comma-separated):
 *
 *   - `skillsetsOnly` (allowlist): when non-empty, a skill passes only if it
 *     belongs to at least one listed set. Unclassified and future sets are
 *     blocked — fail-closed, so a newly vendored skill collection is
 *     invisible until explicitly allowed and trust scoping needs no denylist
 *     maintenance.
 *   - `skillsetsExclude` (denylist): members of the listed sets are dropped;
 *     unclassified skills pass.
 *
 * Both may combine (allowlist minus exceptions). Non-skill URIs (memories/,
 * resources/) always pass.
 *
 * Membership source: a local registry mapping skill name -> set names, kept
 * at `~/.openviking/skillsets.json` (shape `{ "skills": { "<name>":
 * ["set", ...] } }`), regenerated by whatever syncs the skill pool. The path
 * can be overridden with `OPENVIKING_SKILLSETS_REGISTRY`. A missing or
 * unreadable registry means every skill is unclassified: an allowlist then
 * blocks all skills, a denylist blocks none.
 */

import { readFileSync, statSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";

const SKILL_SEGMENT_RE = /\/skills\/([^/]+)/;

let registryCache = null;
let registryCacheMtimeMs = 0;

function registryPath() {
  return process.env.OPENVIKING_SKILLSETS_REGISTRY
    || join(homedir(), ".openviking", "skillsets.json");
}

/**
 * Load the skill -> sets registry, cached on the file's mtime so the hot
 * retrieval paths pay one stat per call at most. Returns null when the
 * registry is absent or malformed.
 */
export function loadSkillsetRegistry() {
  const p = registryPath();
  try {
    const mtimeMs = statSync(p).mtimeMs;
    if (registryCache && mtimeMs === registryCacheMtimeMs) return registryCache;
    registryCache = JSON.parse(readFileSync(p, "utf8"));
    registryCacheMtimeMs = mtimeMs;
    return registryCache;
  } catch {
    registryCache = null;
    registryCacheMtimeMs = 0;
    return null;
  }
}

/**
 * Accept an array of set names or a comma-separated string; trim members and
 * drop empties. Shared by the config, recall, and proxy call sites so the
 * file-config and env forms normalize identically.
 */
export function normalizeSkillsetList(value) {
  if (value == null) return [];
  const raw = Array.isArray(value) ? value : String(value).split(",");
  return raw.map((s) => String(s).trim()).filter(Boolean);
}

function skillSetsOf(uri) {
  const m = SKILL_SEGMENT_RE.exec(String(uri || ""));
  if (!m) return null;
  const sets = loadSkillsetRegistry()?.skills?.[m[1]];
  return Array.isArray(sets) ? sets : null;
}

export function isBlockedSkill(uri, onlySets = [], excludeSets = []) {
  if (!onlySets.length && !excludeSets.length) return false;
  if (!SKILL_SEGMENT_RE.test(String(uri || ""))) return false;
  const sets = skillSetsOf(uri);
  if (onlySets.length && (sets == null || !onlySets.some((s) => sets.includes(s)))) return true;
  if (excludeSets.length && sets != null && excludeSets.some((s) => sets.includes(s))) return true;
  return false;
}

export function filterRecallEntries(entries, onlySets = [], excludeSets = []) {
  if (!onlySets.length && !excludeSets.length) return { entries, dropped: 0 };
  const kept = [];
  let dropped = 0;
  for (const entry of entries) {
    if (isBlockedSkill(entry?.uri, onlySets, excludeSets)) dropped++;
    else kept.push(entry);
  }
  return { entries: kept, dropped };
}

/**
 * Degraded client-side render used only when the server-rendered context
 * block is discarded because it contained blocked skills.
 */
export function renderFilteredEntries(entries) {
  return entries
    .map((e) => {
      const uri = String(e?.uri || "").trim();
      const text = String(e?.text || e?.abstract || "").trim();
      const head = text.length > 200 ? `${text.slice(0, 200)}…` : text;
      return head ? `- ${uri}\n  ${head}` : `- ${uri}`;
    })
    .join("\n");
}

/**
 * Filter the formatted `find` tool output. The server renders one block per
 * hit starting with `- [<type> <NN>%] viking://...`, with indented
 * abstract/content continuation lines (see mcp_endpoint's find renderer);
 * unindented lines (the `Found N item(s):` header, the trailing hint) close
 * the block and pass through untouched. Blocks whose URI is a blocked skill
 * are removed and the header count is rewritten to the surviving total;
 * when nothing is dropped the text is returned as-is.
 */
export function filterFindText(text, onlySets = [], excludeSets = []) {
  if ((!onlySets.length && !excludeSets.length) || typeof text !== "string") return text;
  const lines = text.split("\n");
  const out = [];
  let total = 0;
  let dropped = 0;
  let current = null;
  const flush = () => {
    if (!current) return;
    total++;
    if (isBlockedSkill(current.uri, onlySets, excludeSets)) dropped++;
    else out.push(current.lines.join("\n"));
    current = null;
  };
  for (const line of lines) {
    if (/^- \[.*viking:\/\//.test(line)) {
      flush();
      const uri = (/viking:\/\/[^ )\]]+/.exec(line) || [""])[0];
      current = { uri, lines: [line] };
    } else if (current && (line === "" || /^\s/.test(line))) {
      current.lines.push(line);
    } else {
      flush();
      out.push(line);
    }
  }
  flush();
  if (!dropped) return text;
  const kept = total - dropped;
  return out
    .join("\n")
    .replace(/^Found \d+ item\(s\):/, `Found ${kept} item(s):`);
}
