/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HomeRouteImport } from './routes/home'
import { Route as SessionsRouteRouteImport } from './routes/sessions/route'
import { Route as ResourcesRouteRouteImport } from './routes/resources/route'
import { Route as OperationsRouteRouteImport } from './routes/operations/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionsIndexRouteImport } from './routes/sessions/index'
import { Route as ResourcesIndexRouteImport } from './routes/resources/index'
import { Route as ResourcesAddResourceRouteImport } from './routes/resources/add-resource'

const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRouteRoute = SessionsRouteRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRouteRoute = ResourcesRouteRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsRouteRoute = OperationsRouteRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIndexRoute = SessionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SessionsRouteRoute,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResourcesRouteRoute,
} as any)
const ResourcesAddResourceRoute = ResourcesAddResourceRouteImport.update({
  id: '/add-resource',
  path: '/add-resource',
  getParentRoute: () => ResourcesRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/operations': typeof OperationsRouteRoute
  '/resources': typeof ResourcesRouteRouteWithChildren
  '/sessions': typeof SessionsRouteRouteWithChildren
  '/home': typeof HomeRoute
  '/resources/add-resource': typeof ResourcesAddResourceRoute
  '/resources/': typeof ResourcesIndexRoute
  '/sessions/': typeof SessionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/operations': typeof OperationsRouteRoute
  '/home': typeof HomeRoute
  '/resources/add-resource': typeof ResourcesAddResourceRoute
  '/resources': typeof ResourcesIndexRoute
  '/sessions': typeof SessionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/operations': typeof OperationsRouteRoute
  '/resources': typeof ResourcesRouteRouteWithChildren
  '/sessions': typeof SessionsRouteRouteWithChildren
  '/home': typeof HomeRoute
  '/resources/add-resource': typeof ResourcesAddResourceRoute
  '/resources/': typeof ResourcesIndexRoute
  '/sessions/': typeof SessionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/operations'
    | '/resources'
    | '/sessions'
    | '/home'
    | '/resources/add-resource'
    | '/resources/'
    | '/sessions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/operations'
    | '/home'
    | '/resources/add-resource'
    | '/resources'
    | '/sessions'
  id:
    | '__root__'
    | '/'
    | '/operations'
    | '/resources'
    | '/sessions'
    | '/home'
    | '/resources/add-resource'
    | '/resources/'
    | '/sessions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OperationsRouteRoute: typeof OperationsRouteRoute
  ResourcesRouteRoute: typeof ResourcesRouteRouteWithChildren
  SessionsRouteRoute: typeof SessionsRouteRouteWithChildren
  HomeRoute: typeof HomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations': {
      id: '/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof OperationsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/': {
      id: '/sessions/'
      path: '/'
      fullPath: '/sessions/'
      preLoaderRoute: typeof SessionsIndexRouteImport
      parentRoute: typeof SessionsRouteRoute
    }
    '/resources/': {
      id: '/resources/'
      path: '/'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof ResourcesRouteRoute
    }
    '/resources/add-resource': {
      id: '/resources/add-resource'
      path: '/add-resource'
      fullPath: '/resources/add-resource'
      preLoaderRoute: typeof ResourcesAddResourceRouteImport
      parentRoute: typeof ResourcesRouteRoute
    }
  }
}

interface ResourcesRouteRouteChildren {
  ResourcesAddResourceRoute: typeof ResourcesAddResourceRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
}

const ResourcesRouteRouteChildren: ResourcesRouteRouteChildren = {
  ResourcesAddResourceRoute: ResourcesAddResourceRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
}

const ResourcesRouteRouteWithChildren = ResourcesRouteRoute._addFileChildren(
  ResourcesRouteRouteChildren,
)

interface SessionsRouteRouteChildren {
  SessionsIndexRoute: typeof SessionsIndexRoute
}

const SessionsRouteRouteChildren: SessionsRouteRouteChildren = {
  SessionsIndexRoute: SessionsIndexRoute,
}

const SessionsRouteRouteWithChildren = SessionsRouteRoute._addFileChildren(
  SessionsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OperationsRouteRoute: OperationsRouteRoute,
  ResourcesRouteRoute: ResourcesRouteRouteWithChildren,
  SessionsRouteRoute: SessionsRouteRouteWithChildren,
  HomeRoute: HomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
