# Copyright (c) 2026 Beijing Volcano Engine Technology Co., Ltd.
# SPDX-License-Identifier: AGPL-3.0
"""
Adapter for writing extracted knowledge to OpenViking via ResourceService.
Generates temporary Markdown files and ingests them through the standard resource pipeline.
"""
import os
import tempfile
from datetime import datetime
from typing import Optional

from openviking.daemon.models import ExtractedKnowledge
from openviking.daemon.knowledge_router import KnowledgeRouter
from openviking_cli.utils.logger import get_logger

logger = get_logger(__name__)


class VikingStorageAdapter:
    """Writes structured knowledge to OpenViking via ResourceService.add_resource()."""

    def __init__(self, resource_service):
        self.resource_service = resource_service
        self.router = KnowledgeRouter()

    async def write_knowledge(
        self,
        knowledge: ExtractedKnowledge,
        ctx,
    ) -> bool:
        """
        Write a knowledge item to viking:// storage.

        Args:
            knowledge: The extracted knowledge to write
            ctx: OpenViking RequestContext

        Returns:
            True if successful, False otherwise
        """
        uri = self.router.route(knowledge)
        if not uri:
            logger.warning("Cannot route knowledge: %s", knowledge.title)
            return False

        temp_file = self._generate_temp_markdown(knowledge)

        try:
            await self.resource_service.add_resource(
                path=temp_file,
                ctx=ctx,
                to=uri,
                build_index=True,
                summarize=False,
            )
            logger.info("Knowledge ingested: %s", uri)
            return True

        except Exception as e:
            logger.error("Failed to ingest knowledge to %s: %s", uri, e)
            return False

        finally:
            if os.path.exists(temp_file):
                os.unlink(temp_file)

    def _generate_temp_markdown(self, knowledge: ExtractedKnowledge) -> str:
        """Generate a temporary Markdown file for the knowledge item."""
        fd, path = tempfile.mkstemp(suffix=".md")
        content = self._format_content(knowledge)

        with os.fdopen(fd, "w", encoding="utf-8") as f:
            f.write(content)

        return path

    def _format_content(self, knowledge: ExtractedKnowledge) -> str:
        """Format knowledge content as Markdown based on category."""
        timestamp = datetime.now().isoformat()

        if knowledge.category == "skills":
            return self._format_skill(knowledge, timestamp)
        elif knowledge.category == "memories":
            return self._format_memory(knowledge, timestamp)
        else:
            return self._format_resource(knowledge, timestamp)

    @staticmethod
    def _format_skill(knowledge: ExtractedKnowledge, timestamp: str) -> str:
        """Format a skill knowledge item."""
        steps = ""
        if knowledge.actionable_steps:
            steps = "\n## Steps\n\n"
            for i, step in enumerate(knowledge.actionable_steps, 1):
                steps += f"{i}. {step}\n"
        else:
            steps = "\n## Steps\n\n(No specific steps)\n"

        source = knowledge.source_tool or "Claude Code"

        return f"""# {knowledge.title}

**Extracted**: {timestamp}
**Source**: {source} session
**Confidence**: {knowledge.confidence}

## Content

{knowledge.content}
{steps}
---
*Auto-generated by OpenViking Active Daemon*
"""

    @staticmethod
    def _format_memory(knowledge: ExtractedKnowledge, timestamp: str) -> str:
        """Format a memory knowledge item (append-friendly)."""
        ts = ""
        if knowledge.timestamp:
            try:
                ts = datetime.fromisoformat(knowledge.timestamp).strftime("%Y-%m-%d %H:%M")
            except ValueError:
                ts = timestamp
        else:
            ts = timestamp

        tags = ", ".join(knowledge.entity_links) if knowledge.entity_links else "none"

        return f"""## [{ts}] {knowledge.title}

{knowledge.content}

**Tags**: {tags}

---

"""

    @staticmethod
    def _format_resource(knowledge: ExtractedKnowledge, timestamp: str) -> str:
        """Format a resource knowledge item."""
        tech = knowledge.entity_links[0] if knowledge.entity_links else "general"
        source = knowledge.source_tool or "Claude Code"

        return f"""# {knowledge.title}

**Category**: {tech}
**Extracted**: {timestamp}
**Source**: {source} session

## Content

{knowledge.content}

---
*Auto-generated by OpenViking Active Daemon*
"""
