#!/usr/bin/env node

/**
 * stdio -> streamable-HTTP MCP proxy for the OpenViking Agent Plugins 1.0 package.
 *
 * A conforming Agent Plugins client starts this process as a local stdio MCP
 * server (see ../mcp.json). The proxy reads the same OpenViking credential
 * sources as the ov CLI (OPENVIKING_* env → ~/.openviking/ovcli.conf →
 * ~/.openviking/ov.conf), forwards JSON-RPC requests to the server's /mcp
 * endpoint, and keeps stdout protocol-clean.
 *
 * The modules under ./shared/ are generated by `node
 * examples/memory-plugin-shared/sync.mjs` (this directory is one of its
 * TARGETS) — edit them in examples/memory-plugin-shared/lib, never here.
 */

import { resolve as resolvePath } from "node:path";
import { fileURLToPath } from "node:url";
import { buildProxyConnection } from "./shared/credentials.mjs";
import { createLogger } from "./shared/debug-log.mjs";
import { buildMcpProxyConfig, resolveMcpActorPeerId } from "./shared/mcp-proxy-config.mjs";
import { createOpenVikingMcpProxy } from "./shared/mcp-proxy-core.mjs";

function readProxyConfig() {
  const cfg = buildProxyConnection("agent-plugins", {
    manifestUrl: new URL("../plugin.json", import.meta.url),
  });
  return buildMcpProxyConfig({
    baseUrl: cfg.baseUrl,
    mcpUrl: cfg.mcpUrl,
    apiKey: cfg.apiKey,
    account: cfg.account,
    user: cfg.user,
    sendIdentityHeaders: cfg.sendIdentityHeaders,
    peerId: resolveMcpActorPeerId(cfg),
    userAgent: cfg.userAgent,
    timeoutMs: cfg.timeoutMs,
    debug: cfg.debug,
    debugLogPath: cfg.debugLogPath,
    credentialSource: cfg.credentialSource,
    credentialPath: cfg.credentialPath,
    watchedPaths: cfg.watchedPaths,
  });
}

if (process.argv[1] && fileURLToPath(import.meta.url) === resolvePath(process.argv[1])) {
  createOpenVikingMcpProxy({ readConfig: readProxyConfig, loggerFactory: createLogger }).start();
}
