import React from 'react';
import {
  Article, Lead, P, H2, H3, A, InlineCode, Quote, Table, Callout, Strong, Pre, Ul, Ol, Li,
} from '../../blog-components';

const SLUG = 'agent-managed-context-windows';
const LLM_PATH = `/post/${SLUG}/llm.txt`;
const COVER = `/assets/covers/${SLUG}.webp`;
const CARD_COVER = `/assets/covers/${SLUG}-card.webp`;

const UTM = `utm_source=blog&utm_medium=article&utm_campaign=${SLUG}`;
const OPENVIKING_GITHUB = `https://github.com/volcengine/OpenViking?${UTM}`;
const EXPERIMENT_DIR = `https://github.com/volcengine/OpenViking/tree/main/examples/pi-experimental-context-management?${UTM}`;
const CODEX_RS = 'https://github.com/openai/codex/tree/main/codex-rs';
const PI_REPO = 'https://github.com/earendil-works/pi';
const PI_DOC = {
  en: 'https://docs.openviking.ai/en/agent-integrations/11-pi',
  zh: 'https://docs.openviking.ai/zh/agent-integrations/11-pi',
};
const OPENCLAW_DOC = {
  en: 'https://docs.openviking.ai/en/agent-integrations/03-openclaw',
  zh: 'https://docs.openviking.ai/zh/agent-integrations/03-openclaw',
};
const CONTEXT_DB_POST = '/post/openviking-context-database/';
const SWARM_POST = '/post/agent-swarm-memory/';

// One entry per provider request of the long run, grouped by window:
// context usage in percent of the 128k window pi was told about
// (demo-evidence/pi-ctxwin-demo/demo-long/pressure-timeline.txt).
const PRESSURE = [
  ['w1', [2, 2, 3, 4, 5, 6, 6, 12, 12, 19, 20, 23, 24, 27, 27, 30, 30, 33, 36, 39, 43, 47, 47]],
  ['w2', [4, 7, 8, 8, 9, 9, 13, 17, 21, 25, 27, 28, 28, 29, 30, 30, 30, 35, 39, 39, 40, 40]],
  ['w3', [5, 5, 10, 11, 12, 12, 12, 14, 14, 14, 15, 15, 16, 16, 17, 17, 18, 18, 21, 22, 22, 25, 26, 26, 27, 27, 28, 28, 29, 29, 29, 34, 36, 37, 37, 37, 38, 38, 39, 39, 39, 39, 40, 41, 41, 41, 42, 42]],
  ['w4', [5, 6, 6]],
];

const RESET_LABELS = [
  { zh: '45%，8/22 已完成', en: '45%, 8 of 22 done' },
  { zh: '46%，11/22 已完成', en: '46%, 11 of 22 done' },
  { zh: '22/22 完成，阶段结束', en: '22 of 22 done, phase closed' },
];

const REASONS = [
  'Context window reached ~45% (soft reminder). 8 of 22 files inventoried so far; need a fresh window to finish the remaining 14 files.',
  'Context window at ~46% (soft reminder). 11 of 22 files done (8 from previous window + 3 more …). Need fresh window for remaining 11 files.',
  'Inventory task is fully complete (22/22 files done). User asked a follow-up question about file 1; answering it closes this work phase.',
];

const WINDOW_HEADER = `<openviking-context source="context-window">
<context_window id="w2" previous="w1" archive="archive_001" opened="2026-09-11T05:16:33Z">
This is a fresh context window. The earlier conversation of this session was archived
to OpenViking and is no longer in context. Files, the working directory, running
processes and tools are unchanged.

Reason you gave: Context window reached ~45% (soft reminder). 8 of 22 files
inventoried so far; need a fresh window to finish the remaining 14 files.

Your handoff notes:
<handoff-notes>Goal: Inventory all 22 files under src/ alphabetically — for each file,
read it, append an entry to INVENTORY.md (file name, responsibility, main exports,
risks), and tick the file off in TASK.md.

What is done (8 of 22, ticked in TASK.md, entries appended to INVENTORY.md):
1. src/capture-adapter.mjs — done
   …
Key decisions: Writing INVENTORY.md incrementally (one entry appended per file)
rather than holding until end. …
What remains (14 files, in order):
9. src/context-window-core.test.mjs (85KB — large test file)
   …
Next steps: …</handoff-notes>

The user's most recent message in the previous window was:
<pending-request>Read TASK.md, then work through every file it lists, in order. …
Do not summarise the files you have not read yet.</pending-request>

Working Memory of the archived window, generated by OpenViking:
<working-memory archive="archive_001"># Working Memory
## Session Title
Source inventory of 22 src/ files for OpenViking pi extension
## Current State
8 of 22 src/ files have been inventoried … 14 files remain …
## Task & Goals …
## Key Facts & Decisions …
## Files & Context …
## Errors & Corrections
- INVENTORY.md did not exist at session start (ENOENT error on first read); resolved
  by creating the file before writing the first entry.
- context-window-core.mjs was too large for a single read …; resolved by reading in
  chunks with offset parameter …
## Open Issues …</working-memory>

To recover anything not covered above: history {"action":"list_windows"} /
{"action":"list_items","window":"w1"} / {"action":"read_item","item":"w1:<index>"} /
{"action":"search_contents","query":"..."}.
Continue from the notes above. If the pending request is not finished, resume it now.
</context_window>
</openviking-context>`;

const REPRO = `# OpenViking server URL and key, plus an OpenAI-compatible model endpoint
export OPENVIKING_URL=… OPENVIKING_API_KEY=…
export E2E_LLM_BASE_URL=https://ark.cn-beijing.volces.com/api/v3
export E2E_LLM_API_KEY=… E2E_LLM_MODEL=doubao-seed-2-1-pro-260628 E2E_LLM_API=openai-completions

# the short acceptance gate (a few minutes)
bash examples/pi-experimental-context-management/scripts/e2e-window.sh

# the long task (25–40 minutes)
E2E_WINDOW_LONG=1 E2E_LLM_REASONING=high \\
  bash examples/pi-experimental-context-management/scripts/e2e-window.sh`;

function Styles() {
  return (
    <style>{`
      .amcw *,
      .amcw *::before,
      .amcw *::after {
        box-sizing: border-box;
        min-width: 0;
      }
      .amcw-fig { margin: 36px 0; }
      .amcw-fig__label {
        margin-bottom: 10px;
        color: var(--th-accent);
        font-family: var(--th-font-mono);
        font-size: 11px;
        font-weight: 500;
        letter-spacing: 0.18em;
        text-transform: uppercase;
      }
      .amcw-fig__cap {
        margin-top: 10px;
        color: var(--th-mute);
        font-family: var(--th-font-mono);
        font-size: 13px;
        line-height: 1.5;
      }
      .amcw-quote-zh {
        margin-top: 14px;
        padding-top: 12px;
        border-top: 1px solid var(--th-line);
        color: var(--th-mute);
        font-size: 0.86em;
        line-height: 1.7;
      }
      /* Prose-heavy code samples: keep the tokenizer from painting English words as keywords. */
      .amcw-plain .tk-kw,
      .amcw-plain .tk-ty,
      .amcw-plain .tk-op {
        color: inherit;
        font-weight: inherit;
      }
      .amcw-plain .b-pre__code { flex: 1 1 auto; min-width: 0; }
      .amcw-plain .b-pre__code code { white-space: pre-wrap; overflow-wrap: anywhere; }

      /* SVG charts */
      .amcw-scroll {
        overflow-x: auto;
        border: 1px solid var(--th-line);
        border-radius: var(--th-radius);
        background: color-mix(in oklab, var(--th-bg-2) 70%, var(--th-bg));
      }
      .amcw-scroll svg {
        display: block;
        width: 100%;
        min-width: 560px;
        height: auto;
      }
      .amcw-svg { font-family: var(--th-font-mono); font-size: 12px; }
      .amcw-svg text { fill: var(--th-mute); }
      .amcw-svg .amcw-svg__ink { fill: var(--th-ink); font-weight: 600; }
      .amcw-svg .amcw-svg__grid { stroke: var(--th-line); stroke-width: 1; }
      .amcw-svg .amcw-svg__band { fill: var(--th-ink); opacity: 0.04; }
      .amcw-svg .amcw-svg__line {
        fill: none;
        stroke: var(--th-accent);
        stroke-width: 2;
        stroke-linejoin: round;
        stroke-linecap: round;
      }
      .amcw-svg .amcw-svg__dash { stroke: var(--th-mute); stroke-width: 1; stroke-dasharray: 4 4; fill: none; }
      .amcw-svg .amcw-svg__reset { stroke: var(--th-accent); stroke-width: 1.5; stroke-dasharray: 3 3; fill: none; }
      .amcw-svg .amcw-svg__warn-line { stroke: var(--th-warn); stroke-width: 1; stroke-dasharray: 3 3; fill: none; }
      .amcw-svg .amcw-svg__warn { fill: var(--th-warn); }
      .amcw-svg .amcw-svg__warn-text { fill: var(--th-warn); font-weight: 600; }
      .amcw-svg .amcw-svg__accent-text { fill: var(--th-accent); font-weight: 600; }
      .amcw-svg .amcw-svg__dot { fill: var(--th-accent); stroke: var(--th-bg); stroke-width: 2; }
      .amcw-svg .amcw-svg__ring { fill: var(--th-bg); stroke: var(--th-accent); stroke-width: 2; }
      .amcw-svg .amcw-svg__hit { fill: transparent; }

      /* Figure 1: Codex composition */
      .amcw-map { display: grid; gap: 14px; }
      .amcw-map__row {
        display: grid;
        grid-template-columns: minmax(0, 1fr) auto minmax(0, 2.1fr) auto minmax(0, 1.1fr);
        gap: 10px;
        align-items: center;
      }
      .amcw-node {
        border: 1px solid var(--th-line);
        border-radius: 8px;
        background: color-mix(in oklab, var(--th-bg-2) 88%, transparent);
        padding: 14px;
      }
      .amcw-node__title {
        color: var(--th-ink);
        font-family: var(--th-font-display);
        font-size: 15px;
        font-weight: 700;
        line-height: 1.3;
      }
      .amcw-node__body { margin-top: 6px; color: var(--th-mute); font-size: 13px; line-height: 1.5; }
      .amcw-node__mono { font-family: var(--th-font-mono); font-size: 12px; }
      .amcw-tools { display: grid; gap: 8px; }
      .amcw-tool {
        border: 1px solid var(--th-line);
        border-radius: 6px;
        padding: 10px 12px;
        background: var(--th-bg);
        color: var(--th-mute);
        font-size: 13px;
        line-height: 1.5;
      }
      .amcw-tool__name { color: var(--th-ink); font-family: var(--th-font-mono); font-size: 12.5px; font-weight: 600; }
      .amcw-tool__list { font-family: var(--th-font-mono); font-size: 12px; }
      .amcw-link { color: var(--th-mute); font-size: 18px; line-height: 1; text-align: center; }
      .amcw-link::before { content: '⇄'; }
      .amcw-map__windows {
        display: grid;
        grid-template-columns: minmax(0, 1fr) minmax(0, 1.25fr) minmax(0, 1fr);
        gap: 10px;
        align-items: stretch;
      }
      .amcw-win {
        border: 1px dashed var(--th-line);
        border-radius: 8px;
        padding: 12px 14px;
        color: var(--th-mute);
        font-size: 13px;
        line-height: 1.5;
      }
      .amcw-win--open { border-style: solid; }
      .amcw-win__title { color: var(--th-ink); font-family: var(--th-font-mono); font-size: 12px; font-weight: 600; }
      .amcw-handoff {
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        gap: 4px;
        padding: 0 6px;
        color: var(--th-mute);
        font-size: 12.5px;
        line-height: 1.45;
        text-align: center;
      }
      .amcw-handoff__arrow { color: var(--th-accent); font-size: 22px; line-height: 1; }
      .amcw-handoff__tag { color: var(--th-ink); font-family: var(--th-font-mono); font-size: 12px; }

      /* Figure 3: window anatomy */
      .amcw-anat { display: grid; grid-template-columns: minmax(0, 1fr); gap: 14px; }
      .amcw-panel {
        border: 1px solid var(--th-line);
        border-radius: 8px;
        background: color-mix(in oklab, var(--th-bg-2) 88%, transparent);
        padding: 12px 14px;
        color: var(--th-mute);
        font-family: var(--th-font-mono);
        font-size: 12.5px;
        line-height: 1.6;
      }
      .amcw-panel__title {
        margin-bottom: 8px;
        color: var(--th-ink);
        font-family: var(--th-font-display);
        font-size: 14px;
        font-weight: 700;
      }
      .amcw-block {
        margin-top: 8px;
        border: 1px solid var(--th-line);
        border-radius: 6px;
        background: var(--th-bg);
        padding: 8px 10px;
      }
      .amcw-block--head { border-color: color-mix(in oklab, var(--th-accent) 55%, var(--th-line)); }
      .amcw-block__title { color: var(--th-ink); font-weight: 600; }
      .amcw-block__sub { font-family: var(--th-font-body); font-size: 12px; }
      .amcw-row { display: flex; gap: 8px; align-items: baseline; }
      .amcw-row--i1 { padding-left: 14px; }
      .amcw-row--i2 { padding-left: 28px; }
      .amcw-row--i3 { padding-left: 42px; }
      .amcw-row__k { flex: 0 1 auto; color: var(--th-ink); overflow-wrap: anywhere; }
      .amcw-row__v { font-family: var(--th-font-body); font-size: 12.5px; }
      .amcw-badge {
        display: inline-flex;
        flex: none;
        align-items: center;
        justify-content: center;
        width: 18px;
        height: 18px;
        border-radius: 999px;
        background: var(--th-accent);
        color: var(--th-bg);
        font-family: var(--th-font-mono);
        font-size: 11px;
        font-weight: 700;
        transform: translateY(2px);
      }
      .amcw-badge--b { background: var(--th-accent-2); }

      /* Results */
      .amcw-stats { display: grid; grid-template-columns: repeat(4, minmax(0, 1fr)); gap: 12px; margin: 28px 0; }
      .amcw-stat {
        border: 1px solid var(--th-line);
        border-radius: 8px;
        background: color-mix(in oklab, var(--th-bg-2) 88%, transparent);
        padding: 14px;
      }
      .amcw-stat__num {
        color: var(--th-ink);
        font-family: var(--th-font-display);
        font-size: 26px;
        font-weight: 700;
        letter-spacing: -0.01em;
        line-height: 1.1;
      }
      .amcw-stat__label { margin-top: 6px; color: var(--th-mute); font-size: 13px; line-height: 1.45; }

      @media (max-width: 840px) {
        .amcw-stats { grid-template-columns: repeat(2, minmax(0, 1fr)); }
      }
      @media (max-width: 720px) {
        .amcw-map__row { grid-template-columns: 1fr; }
        .amcw-link::before { content: '⇅'; }
        .amcw-map__windows { grid-template-columns: 1fr; }
        .amcw-handoff { padding: 6px 0; }
        .amcw-handoff__arrow { transform: rotate(90deg); }
      }
    `}</style>
  );
}

function Fig({ label, caption, children }) {
  return (
    <div className="amcw-fig" role="figure" aria-label={label}>
      <div className="amcw-fig__label">{label}</div>
      {children}
      {caption ? <div className="amcw-fig__cap">{caption}</div> : null}
    </div>
  );
}

/* ---------- Figure 1: what Codex ships ---------- */

function CodexMap({ t }) {
  return (
    <Fig
      label={t({ zh: 'Codex 实验性上下文管理的组成', en: 'What Codex’s experimental context management is made of' })}
      caption={t({
        zh: '工具、提示词和存储都来自 harness。换窗时，旧窗口整体留在 history 里，新窗口只带一个 <context_window> 块过去。',
        en: 'Tools, prompts, and storage all come from the harness. At a reset the old window stays whole in history; only a <context_window> block travels to the new one.',
      })}
    >
      <div className="amcw-map">
        <div className="amcw-map__row">
          <div className="amcw-node">
            <div className="amcw-node__title">{t({ zh: '模型', en: 'Model' })}</div>
            <div className="amcw-node__body">GPT-6 Astra</div>
            <div className="amcw-node__body">{t({ zh: '决定何时翻页、翻页前记什么、翻页后去哪找', en: 'Decides when to turn the page, what to write down first, and where to look afterwards' })}</div>
          </div>
          <div className="amcw-link" aria-hidden="true" />
          <div className="amcw-tools">
            <div className="amcw-tool">
              <span className="amcw-tool__name">notes</span>
              <div className="amcw-tool__list">write_file · append_to_file · read_file · search_contents · list_files_by_prefix</div>
              <div>{t({ zh: '跨窗口存活的私有草稿纸', en: 'A private scratchpad that survives across windows' })}</div>
            </div>
            <div className="amcw-tool">
              <span className="amcw-tool__name">history</span>
              <div className="amcw-tool__list">list_windows · list_items · read_item · search_contents</div>
              <div>{t({ zh: '按窗口 ID 和条目 ID 回读已关闭的窗口', en: 'Reads closed windows back by window id and item id' })}</div>
            </div>
            <div className="amcw-tool">
              <span className="amcw-tool__name">new_context</span>
              {' · '}
              <span className="amcw-tool__name">get_context_remaining</span>
              <div>{t({ zh: '无参数地开一个新窗口；查询剩余 token 数', en: 'Open a new window with no parameters; ask how many tokens are left' })}</div>
            </div>
          </div>
          <div className="amcw-link" aria-hidden="true" />
          <div className="amcw-node">
            <div className="amcw-node__title">{t({ zh: 'OpenAI 后端存储', en: 'OpenAI backend storage' })}</div>
            <div className="amcw-node__body amcw-node__mono">alpha/notes/v2/*</div>
            <div className="amcw-node__body amcw-node__mono">alpha/history/v2/*</div>
            <div className="amcw-node__body">{t({ zh: '所以目前只对 ChatGPT Plus/Pro 开放', en: 'Which is why it is limited to ChatGPT Plus/Pro today' })}</div>
          </div>
        </div>
        <div className="amcw-map__windows">
          <div className="amcw-win">
            <div className="amcw-win__title">{t({ zh: '窗口 1（已关闭）', en: 'Window 1 (closed)' })}</div>
            <div>{t({ zh: '整个对话原样进入 history，包括每一条工具输出。没有任何一步让 LLM 写摘要。', en: 'The whole conversation goes into history as is, tool output included. No LLM writes a summary at any step.' })}</div>
          </div>
          <div className="amcw-handoff">
            <div className="amcw-handoff__arrow" aria-hidden="true">→</div>
            <div className="amcw-handoff__tag">{'<context_window>'}</div>
            <div>{t({ zh: '当前和上一个窗口的 ID，加一段从 notes 取出的 thread_hint（≤ 4000 字节）', en: 'Current and previous window ids, plus a thread_hint pulled from notes (≤ 4000 bytes)' })}</div>
          </div>
          <div className="amcw-win amcw-win--open">
            <div className="amcw-win__title">{t({ zh: '窗口 2（新开）', en: 'Window 2 (fresh)' })}</div>
            <div>{t({ zh: 'system/developer prompt、环境状态、保留的客户端消息，外加那个 <context_window> 块。', en: 'System/developer prompt, environment state, retained client messages, plus that <context_window> block.' })}</div>
          </div>
        </div>
      </div>
    </Fig>
  );
}

/* ---------- Figure 2: threshold compaction vs. resets at task boundaries ---------- */

function TimelineCompare({ t }) {
  const W = 720;
  const H = 300;
  const L = 44;
  const R = 16;
  const pw = W - L - R;
  const xf = f => L + f * pw;
  const tasks = [[0, 0.25], [0.25, 0.5], [0.5, 0.71], [0.71, 1]];
  const taskNames = [
    t({ zh: '任务 A', en: 'Task A' }),
    t({ zh: '任务 B', en: 'Task B' }),
    t({ zh: '任务 C', en: 'Task C' }),
    t({ zh: '任务 D', en: 'Task D' }),
  ];
  const panel = top => ({ top, h: 96, y: p => top + 96 - (p / 100) * 96 });
  const pa = panel(30);
  const pb = panel(180);
  const compactAt = [0.375, 0.86];
  const cpath = [
    `M${xf(0)} ${pa.y(5)}`,
    `L${xf(compactAt[0])} ${pa.y(90)}`,
    `L${xf(compactAt[0])} ${pa.y(35)}`,
    `L${xf(compactAt[1])} ${pa.y(90)}`,
    `L${xf(compactAt[1])} ${pa.y(35)}`,
    `L${xf(1)} ${pa.y(50)}`,
  ].join(' ');
  const peaks = [48, 62, 40, 55];
  const bpath = tasks.map(([a, b], i) => `M${xf(a)} ${pb.y(5)} L${xf(b)} ${pb.y(peaks[i])}`).join(' ');

  const bands = p => tasks.map(([a, b], i) => (
    <g key={i}>
      {i % 2 ? <rect className="amcw-svg__band" x={xf(a)} y={p.top} width={xf(b) - xf(a)} height={p.h} /> : null}
      <text x={(xf(a) + xf(b)) / 2} y={p.top + p.h + 15} textAnchor="middle">{taskNames[i]}</text>
    </g>
  ));
  const frame = p => (
    <g>
      <line className="amcw-svg__grid" x1={L} x2={W - R} y1={p.top + p.h} y2={p.top + p.h} />
      <line className="amcw-svg__grid" x1={L} x2={W - R} y1={p.top} y2={p.top} />
      <text x={L - 6} y={p.top + p.h + 4} textAnchor="end">0%</text>
      <text x={L - 6} y={p.top + 4} textAnchor="end">100%</text>
    </g>
  );

  return (
    <Fig
      label={t({ zh: '两种时间线', en: 'Two timelines' })}
      caption={t({
        zh: '上：按阈值压缩，上下文一路涨到阈值，压缩点落在任务中间，之后从一份摘要继续涨。下：在任务边界翻页，每个任务都从一个几乎空的窗口开始。',
        en: 'Top: threshold compaction. Context climbs to the threshold, the compaction lands in the middle of a task, and the climb resumes from a summary. Bottom: resets at task boundaries. Every task starts in a nearly empty window.',
      })}
    >
      <div className="amcw-scroll">
        <svg className="amcw-svg" viewBox={`0 0 ${W} ${H}`} role="img" aria-label={t({ zh: '阈值压缩与任务边界翻页的上下文占用曲线对比', en: 'Context usage under threshold compaction versus resets at task boundaries' })}>
          <text className="amcw-svg__ink" x={L} y={18}>{t({ zh: '按阈值压缩', en: 'Threshold compaction' })}</text>
          {bands(pa)}
          {frame(pa)}
          <line className="amcw-svg__warn-line" x1={L} x2={W - R} y1={pa.y(90)} y2={pa.y(90)} />
          <text className="amcw-svg__warn-text" x={W - R} y={pa.y(90) - 5} textAnchor="end">{t({ zh: '压缩阈值 90%', en: 'compaction threshold 90%' })}</text>
          <path className="amcw-svg__line" d={cpath} />
          {compactAt.map((f, i) => <circle key={i} className="amcw-svg__warn" cx={xf(f)} cy={pa.y(90)} r={4.5} />)}
          <text className="amcw-svg__warn-text" x={xf(compactAt[0]) + 9} y={pa.y(90) + 20}>{t({ zh: '压缩点落在任务 B 中间', en: 'compaction lands mid-task B' })}</text>
          <text x={xf(compactAt[0]) + 9} y={pa.y(35) + 4}>{t({ zh: '从摘要继续', en: 'resumes from a summary' })}</text>

          <text className="amcw-svg__ink" x={L} y={168}>{t({ zh: '在任务边界翻页', en: 'Reset at task boundaries' })}</text>
          {bands(pb)}
          {frame(pb)}
          <path className="amcw-svg__line" d={bpath} />
          {tasks.slice(0, -1).map(([, b], i) => (
            <g key={i}>
              <line className="amcw-svg__reset" x1={xf(b)} x2={xf(b)} y1={pb.y(peaks[i])} y2={pb.y(5)} />
              <circle className="amcw-svg__dot" cx={xf(b)} cy={pb.y(peaks[i])} r={4.5} />
              <text className="amcw-svg__accent-text" x={xf(b)} y={pb.y(peaks[i]) - 8} textAnchor="middle">new_context</text>
            </g>
          ))}
        </svg>
      </div>
    </Fig>
  );
}

/* ---------- Figure 3: what the model sees vs. what OpenViking keeps ---------- */

function Badge({ kind }) {
  return <span className={`amcw-badge ${kind === 'B' ? 'amcw-badge--b' : ''}`} aria-label={kind}>{kind}</span>;
}

function Row({ indent = 0, k, v, badge }) {
  return (
    <div className={`amcw-row ${indent ? `amcw-row--i${indent}` : ''}`}>
      <span className="amcw-row__k">{k}</span>
      {v ? <span className="amcw-row__v">{v}</span> : null}
      {badge ? <Badge kind={badge} /> : null}
    </div>
  );
}

function WindowAnatomy({ t }) {
  return (
    <Fig
      label={t({ zh: '换窗之后：模型看到的请求 vs. OpenViking 里的 session', en: 'After a reset: the request the model sees vs. the session in OpenViking' })}
      caption={t({
        zh: 'A：窗口头里的 Working Memory 就是 archive_001/.overview.md。B：history 的 read_item 和 search_contents 读的是 messages.jsonl。上一个窗口从活跃列表里消失了，但完整地留在右边。',
        en: 'A: the Working Memory in the window header is archive_001/.overview.md. B: history’s read_item and search_contents read messages.jsonl. The previous window is gone from the active list, and kept in full on the right.',
      })}
    >
      <div className="amcw-anat">
        <div className="amcw-panel">
          <div className="amcw-panel__title">{t({ zh: '模型看到的一份请求', en: 'One request, as the model sees it' })}</div>
          <div className="amcw-block">
            <div className="amcw-block__title">system prompt</div>
            <Row indent={1} k="├ " v={t({ zh: 'Pi 原生的 system prompt', en: 'Pi’s own system prompt' })} />
            <Row indent={1} k="└ <context-window-management>" v={t({ zh: '常驻指导，整个 session 不变', en: 'standing guidance, unchanged all session' })} />
          </div>
          <div className="amcw-block amcw-block--head">
            <div className="amcw-block__title">{t({ zh: '窗口头', en: 'window header' })} <span className="amcw-block__sub">{t({ zh: '一条 user 消息，w2 及之后的窗口才有', en: 'one user message, present from w2 on' })}</span></div>
            <Row indent={1} k={'<context_window id="w2" previous="w1" archive="archive_001">'} />
            <Row indent={2} k="├ Reason you gave" v={t({ zh: '模型自己写的换窗理由', en: 'the reason the model gave' })} />
            <Row indent={2} k="├ <handoff-notes>" v={t({ zh: '模型自己写的交接笔记', en: 'the model’s own handoff notes' })} />
            <Row indent={2} k="├ <pending-request>" v={t({ zh: '上一窗口里用户最后一条消息', en: 'the user’s last message in the old window' })} />
            <Row indent={2} k="├ <working-memory>" v={t({ zh: 'OpenViking 从完整归档生成', en: 'generated by OpenViking from the full archive' })} badge="A" />
            <Row indent={2} k="└ history …" v={t({ zh: '还缺什么，去 archive_001 里读', en: 'how to read the rest from archive_001' })} badge="B" />
          </div>
          <div className="amcw-block">
            <div className="amcw-block__title">{t({ zh: '本窗口的活跃消息', en: 'active messages of this window' })}</div>
            <Row indent={1} k="├ user / assistant / tool" v={t({ zh: '从换窗那一刻开始', en: 'from the moment of the reset' })} />
            <Row indent={1} k="├ [context-status]" v={t({ zh: '每条 user 消息后一行', en: 'one line after every user message' })} />
            <Row indent={1} k="├ [context-reminder]" v={t({ zh: '至多一条软提醒、一条硬提醒', en: 'at most one soft and one hard' })} />
            <Row indent={1} k="└ <openviking-context>" v={t({ zh: 'auto-recall 注入的记忆块', en: 'memory blocks injected by auto-recall' })} />
          </div>
        </div>
        <div className="amcw-panel">
          <div className="amcw-panel__title">{t({ zh: 'OpenViking 里的 session 目录', en: 'The session directory in OpenViking' })}</div>
          <Row k="viking://user/<uid>/sessions/pi-<session>/" />
          <Row indent={1} k="└ history/" />
          <Row indent={2} k="├ archive_001/" />
          <Row indent={3} k="├ .abstract.md" v={t({ zh: '一句话，list_windows 时就能看到', en: 'one line, visible from list_windows' })} />
          <Row indent={3} k="├ .overview.md" v={t({ zh: '七段式 Working Memory，进了窗口头', en: 'seven-section Working Memory, goes into the header' })} badge="A" />
          <Row indent={3} k="└ messages.jsonl" v={t({ zh: '完整原文，包括每一条工具输出', en: 'the full transcript, every tool output included' })} badge="B" />
          <Row indent={2} k="├ archive_002/" />
          <Row indent={2} k="└ archive_003/" />
        </div>
      </div>
    </Fig>
  );
}

/* ---------- Figure 4: the pressure curve of the long run ---------- */

function PressureChart({ t }) {
  const W = 720;
  const H = 260;
  const L = 44;
  const R = 12;
  const T = 30;
  const B = 42;
  const pw = W - L - R;
  const ph = H - T - B;
  const yMax = 60;
  const all = PRESSURE.flatMap(([w, arr]) => arr.map(p => ({ w, p })));
  const n = all.length;
  const xOf = i => L + (i * pw) / (n - 1);
  const yOf = p => T + ph - (p / yMax) * ph;

  let cursor = 0;
  const ranges = PRESSURE.map(([w, arr]) => {
    const r = { w, from: cursor, to: cursor + arr.length - 1 };
    cursor += arr.length;
    return r;
  });
  const paths = ranges.map(r => all
    .slice(r.from, r.to + 1)
    .map((d, j) => `${j ? 'L' : 'M'}${xOf(r.from + j).toFixed(1)} ${yOf(d.p).toFixed(1)}`)
    .join(' '));
  const resets = ranges.slice(0, -1).map((r, i) => ({
    x: (xOf(r.to) + xOf(r.to + 1)) / 2,
    lastIdx: r.to,
    label: t(RESET_LABELS[i]),
  }));
  const probe = ranges[2].from + PRESSURE[2][1].findIndex(p => p >= 32);
  const ticks = [0, 20, 40, 60];
  const xticks = [1, 20, 40, 60, 80, 96];

  return (
    <Fig
      label={t({ zh: '长任务的上下文压力曲线', en: 'Context pressure across the long run' })}
      caption={t({
        zh: '96 次请求，纵轴是每次请求的上下文占用（按报文字节数 / 4 估算，相对 128k）。三处虚线是模型自己调用 new_context 的位置，标注的是它给出的理由。软提醒阈值压到了 45%。',
        en: '96 provider requests; the y axis is context usage per request (payload bytes / 4, against the 128k window). The three dashed lines are where the model called new_context itself, annotated with the reason it gave. The soft reminder threshold was lowered to 45%.',
      })}
    >
      <div className="amcw-scroll">
        <svg className="amcw-svg" viewBox={`0 0 ${W} ${H}`} role="img" aria-label={t({ zh: '96 次请求的上下文占用锯齿图，三次换窗处占用从约 45% 回落到 5%', en: 'Saw-tooth chart of context usage over 96 requests, dropping from about 45% to 5% at each of three resets' })}>
          {ticks.map(v => (
            <g key={v}>
              <line className="amcw-svg__grid" x1={L} x2={W - R} y1={yOf(v)} y2={yOf(v)} />
              <text x={L - 6} y={yOf(v) + 4} textAnchor="end">{v}%</text>
            </g>
          ))}
          {xticks.map(v => (
            <text key={v} x={xOf(v - 1)} y={T + ph + 16} textAnchor="middle">{v}</text>
          ))}
          <text x={L + pw / 2} y={H - 8} textAnchor="middle">{t({ zh: '发给模型的请求序号', en: 'provider request' })}</text>

          <line className="amcw-svg__warn-line" x1={L} x2={W - R} y1={yOf(45)} y2={yOf(45)} />
          <text className="amcw-svg__warn-text" x={W - R} y={yOf(45) - 5} textAnchor="end">{t({ zh: '软提醒 45%', en: 'soft reminder 45%' })}</text>

          {ranges.map((r, i) => (
            <g key={r.w}>
              <path className="amcw-svg__line" d={paths[i]} />
              <text className="amcw-svg__ink" x={xOf(r.from) + (i === ranges.length - 1 ? -2 : 4)} y={T + ph - 6} textAnchor={i === ranges.length - 1 ? 'end' : 'start'}>{r.w}</text>
            </g>
          ))}

          {resets.map((rs, i) => (
            <g key={i}>
              <line className="amcw-svg__reset" x1={rs.x} x2={rs.x} y1={T - 4} y2={T + ph} />
              <circle className="amcw-svg__dot" cx={xOf(rs.lastIdx)} cy={yOf(all[rs.lastIdx].p)} r={4} />
              <text className="amcw-svg__accent-text" x={rs.x + (i === resets.length - 1 ? -6 : 6)} y={T - 10} textAnchor={i === resets.length - 1 ? 'end' : 'start'}>{rs.label}</text>
            </g>
          ))}

          <circle className="amcw-svg__ring" cx={xOf(probe)} cy={yOf(all[probe].p)} r={5} />
          <text x={xOf(probe) - 10} y={yOf(all[probe].p) - 12} textAnchor="end">{t({ zh: 'get_context_remaining → no action needed', en: 'get_context_remaining → no action needed' })}</text>

          {all.map((d, i) => (
            <circle key={i} className="amcw-svg__hit" cx={xOf(i)} cy={yOf(d.p)} r={6}>
              <title>{`${d.w} · ${t({ zh: '请求', en: 'request' })} ${i + 1} · ${d.p}%`}</title>
            </circle>
          ))}
        </svg>
      </div>
    </Fig>
  );
}

/* ---------- Results ---------- */

function StatStrip({ t }) {
  const stats = [
    { num: '96', label: { zh: '发给模型的请求', en: 'provider requests' } },
    { num: '3', label: { zh: '模型自己换窗的次数，w1 → w4', en: 'resets, all chosen by the model, w1 → w4' } },
    { num: '47%', label: { zh: '峰值上下文，约 60.1k / 128k token', en: 'peak context, about 60.1k of 128k tokens' } },
    { num: '≈5k', label: { zh: '换窗后的上下文 token', en: 'tokens right after a reset' } },
    { num: '3', label: { zh: 'OpenViking 里的归档，每段都有 Working Memory', en: 'archives in OpenViking, each with a Working Memory' } },
    { num: '22/22', label: { zh: 'INVENTORY.md 收录的文件，TASK.md 全部打勾', en: 'files in INVENTORY.md, TASK.md fully ticked' } },
    { num: '23 min', label: { zh: '总耗时，其中三次等 Working Memory 各 50 s、90 s、66 s', en: 'wall clock, including three Working Memory waits of 50 s, 90 s, and 66 s' } },
    { num: '0', label: { zh: '进入模型上下文的压缩摘要', en: 'compacted summaries that entered the model’s context' } },
  ];
  return (
    <div className="amcw-stats" role="figure" aria-label={t({ zh: '长任务的运行结果', en: 'Results of the long run' })}>
      {stats.map(s => (
        <div className="amcw-stat" key={s.label.en}>
          <div className="amcw-stat__num">{s.num}</div>
          <div className="amcw-stat__label">{t(s.label)}</div>
        </div>
      ))}
    </div>
  );
}

/* ---------- The article ---------- */

function AgentManagedContextWindows({ t, lang }) {
  return (
    <Article className="amcw">
      <Styles />

      <Lead>{t({
        zh: '上下文快满了怎么办？过去的答案是 harness 按阈值压缩对话。Codex 在 GPT-6 Astra 上换了一种做法：模型自己决定何时开新窗口，旧窗口原样留在模型之外。我们在 Pi 上用 OpenViking 的 session 归档复刻了这套机制。',
        en: 'What happens when the context window fills up? The usual answer is that the harness compacts the conversation at a threshold. With GPT-6 Astra, Codex tries something else: the model decides when to open a new window, and the old one is kept intact outside the model. We rebuilt that mechanism on Pi with OpenViking’s session archive.',
      })}</Lead>

      <H2>{t({ zh: 'Codex 为了 GPT-6 Astra 改了什么', en: 'What Codex changed for GPT-6 Astra' })}</H2>

      <P>{t({
        zh: 'OpenAI 在 GPT-6 Astra 的模型文档里，为 Codex 新增了一节「experimental context management」（实验性上下文管理）。原文只有两句：',
        en: 'In the GPT-6 Astra model documentation, OpenAI added a section for Codex called “experimental context management”. The original is two sentences:',
      })}</P>

      <Quote>
        On supported Codex clients, users signed in with ChatGPT Plus or Pro can opt in to experimental
        context management. Astra keeps notes across context windows and can search earlier messages and
        tool results from the same task.
        {lang === 'zh' ? (
          <div className="amcw-quote-zh">
            在受支持的 Codex 客户端上，用 ChatGPT Plus 或 Pro 登录的用户可以开启实验性上下文管理。Astra
            会跨上下文窗口记笔记，也能搜索同一任务中早先的消息和工具输出。
          </div>
        ) : null}
      </Quote>

      <P>{t({
        zh: <>开关在 <InlineCode>config.toml</InlineCode> 里（<InlineCode>features.context_management.experimental_mode = true</InlineCode>）。发布初期只对 ChatGPT Plus/Pro 账号生效，Business、Enterprise 和 API key 登录暂不支持。</>,
        en: <>The switch lives in <InlineCode>config.toml</InlineCode> (<InlineCode>features.context_management.experimental_mode = true</InlineCode>). At launch it only works for ChatGPT Plus/Pro accounts; Business, Enterprise, and API-key logins are not supported yet.</>,
      })}</P>

      <P>{t({
        zh: <>官方文档的措辞把这归功于模型本身：Astra「会跨窗口记笔记」、「能搜索早先的消息和工具输出」。但 Codex 的 harness 是开源的，翻一下 <A href={CODEX_RS}>codex-rs</A> 的源码，就能看到模型之外的另一半是怎么搭的：</>,
        en: <>The documentation credits the model: Astra “keeps notes across context windows” and “can search earlier messages and tool results”. But the Codex harness is open source, and reading <A href={CODEX_RS}>codex-rs</A> shows how the other half, the part outside the model, is built:</>,
      })}</P>

      <Ul>
        <Li>{t({
          zh: <><Strong>模型看到的工具。</Strong><InlineCode>notes</InlineCode> 命名空间（<InlineCode>write_file</InlineCode> / <InlineCode>append_to_file</InlineCode> / <InlineCode>read_file</InlineCode> / <InlineCode>search_contents</InlineCode> / <InlineCode>list_files_by_prefix</InlineCode>）是一块跨窗口存活的私有草稿纸；<InlineCode>history</InlineCode> 命名空间（<InlineCode>list_windows</InlineCode> / <InlineCode>list_items</InlineCode> / <InlineCode>read_item</InlineCode> / <InlineCode>search_contents</InlineCode>）按窗口 ID 和条目 ID 回读已关闭的窗口；<InlineCode>new_context</InlineCode> 没有任何参数，描述只有一句 “Start a new context window. Does not clear, reset, or otherwise affect environment state.”；<InlineCode>get_context_remaining</InlineCode> 返回当前剩余的 token 数。</>,
          en: <><Strong>The tools the model sees.</Strong> The <InlineCode>notes</InlineCode> namespace (<InlineCode>write_file</InlineCode> / <InlineCode>append_to_file</InlineCode> / <InlineCode>read_file</InlineCode> / <InlineCode>search_contents</InlineCode> / <InlineCode>list_files_by_prefix</InlineCode>) is a private scratchpad that survives across windows. The <InlineCode>history</InlineCode> namespace (<InlineCode>list_windows</InlineCode> / <InlineCode>list_items</InlineCode> / <InlineCode>read_item</InlineCode> / <InlineCode>search_contents</InlineCode>) reads closed windows back by window id and item id. <InlineCode>new_context</InlineCode> takes no parameters and is described in one line: “Start a new context window. Does not clear, reset, or otherwise affect environment state.” <InlineCode>get_context_remaining</InlineCode> returns the tokens left.</>,
        })}</Li>
        <Li>{t({
          zh: <><Strong>换窗时发生了什么。</Strong>调用 <InlineCode>new_context</InlineCode> 只是设了一个标志位。本次采样结束后，session 直接装载一个全新的窗口：system/developer prompt、环境状态、保留的客户端消息，外加一个 <InlineCode>{'<context_window>'}</InlineCode> 块。这个块里有当前和上一个窗口的 ID，以及从 notes 后端取出的一段 <InlineCode>thread_hint</InlineCode>（不超过 4000 字节）。<Strong>整个切换过程没有任何一步让 LLM 生成摘要。</Strong></>,
          en: <><Strong>What happens at a reset.</Strong> Calling <InlineCode>new_context</InlineCode> only sets a flag. Once the current sampling finishes, the session loads a brand-new window: the system/developer prompt, environment state, retained client messages, plus a <InlineCode>{'<context_window>'}</InlineCode> block holding the current and previous window ids and a <InlineCode>thread_hint</InlineCode> pulled from the notes backend (at most 4000 bytes). <Strong>At no step of the switch does an LLM write a summary.</Strong></>,
        })}</Li>
        <Li>{t({
          zh: <><Strong>提示词。</Strong>一段常驻 guidance 引导模型在 notes 里维护 checkpoint（目标、决策、进度、收获、下一步，以及尚未完成的用户请求）。模型一旦看到「上一个窗口 ID」，就知道发生过切换，要先读 checkpoint，再用 history 补细节；剩余空间不足 6144 token 时，系统提醒一次「先存 notes，再调 new_context」；token 实在耗尽时，额外给 16384 token 的缓冲，强制模型只做一次 notes 写入，然后立刻换窗。</>,
          en: <><Strong>The prompts.</Strong> A standing guidance message tells the model to keep a checkpoint in notes (goal, decisions, progress, learnings, next steps, and any unfinished user requests). When the model sees a previous-window id it knows a reset happened: read the checkpoint first, then fill the gaps with history. When fewer than 6144 tokens remain, a reminder fires once: save notes, then call <InlineCode>new_context</InlineCode>. When nothing is left, an extra 16384-token buffer is granted and the model is forced to make exactly one notes write followed by a reset.</>,
        })}</Li>
        <Li>{t({
          zh: <><Strong>存储在 OpenAI 后端</Strong>（<InlineCode>alpha/notes/v2/*</InlineCode>、<InlineCode>alpha/history/v2/*</InlineCode>），这也是它目前只对 ChatGPT Plus/Pro 开放的原因。</>,
          en: <><Strong>Storage lives on OpenAI’s backend</Strong> (<InlineCode>alpha/notes/v2/*</InlineCode>, <InlineCode>alpha/history/v2/*</InlineCode>), which is why the feature is currently limited to ChatGPT Plus/Pro logins.</>,
        })}</Li>
      </Ul>

      <P>{t({
        zh: <>所以「能力内化于模型」和「harness 搭脚手架」并不矛盾：工具、提示词和存储都由 harness 提供，模型的价值在于被训练得会用这套工具、判断得准。真正的变化在于，<Strong>控制权从 harness 的固定规则交到了模型手里</Strong>：何时翻页、翻页前记什么、翻页后去哪找回细节，都由模型决定。支撑这些决策的，是一个独立于模型之外、装得下全部历史的存储。</>,
        en: <>So “the capability is in the model” and “the harness builds the scaffolding” are not in conflict. The tools, prompts, and storage come from the harness; the model’s contribution is that it was trained to use them and to judge well. The real shift is that <Strong>control moves from fixed harness rules to the model</Strong>: when to turn the page, what to write down before doing so, and where to recover details afterwards are all the model’s decisions. What makes those decisions possible is storage outside the model that holds the entire history.</>,
      })}</P>

      <CodexMap t={t} />

      <H2>{t({ zh: '在此之前：按阈值压缩，以及它的三个问题', en: 'Before this: threshold compaction and its three problems' })}</H2>

      <P>{t({
        zh: <>长期以来，主流 harness（包括 Codex 自己、Claude Code，以及绝大多数开源 coding agent）处理超长对话的办法都是同一个：<Strong>压缩</Strong>。无论是用户手动输入 <InlineCode>/compact</InlineCode>，还是上下文占用触及预设阈值，harness 都会让模型把整段对话重写成一份摘要，再用摘要替换原始上下文，继续处理后面的请求。</>,
        en: <>For a long time, mainstream harnesses (Codex itself, Claude Code, and most open-source coding agents) have handled long conversations the same way: <Strong>compaction</Strong>. Whether the user types <InlineCode>/compact</InlineCode> or context usage crosses a preset threshold, the harness has the model rewrite the whole conversation as a summary, swaps the summary in for the original context, and carries on.</>,
      })}</P>

      <P>{t({
        zh: '这个办法简单可靠，但有三个绕不开的问题：',
        en: 'It is simple and dependable, and it has three problems that do not go away:',
      })}</P>

      <Ol>
        <Li>{t({
          zh: <><Strong>信息有损。</Strong>摘要由模型生成，而且写摘要和干活的往往是同一个模型。压缩时被判断为「不重要」而丢掉的细节，事后再也找不回来。工具输出最容易被抹掉，而精确的文件路径、报错日志和关键数值恰恰藏在这些输出里。</>,
          en: <><Strong>It loses information.</Strong> The summary is written by a model, usually the same one doing the work. Details it judged unimportant at compaction time are gone for good. Tool output is the first thing to be dropped, and that is exactly where the exact file paths, error logs, and key numbers live.</>,
        })}</Li>
        <Li>{t({
          zh: <><Strong>触发时机脱离任务。</Strong>压缩阈值只看 token 数，不关心任务进行到哪一步。对助手类 Agent，一个窗口里可能交织着多个话题，机械压缩会把它们搅在一起；对 coding agent，压缩经常落在某个阶段的半截，比如刚改完三个文件、还没跑测试。一波压缩之后，模型对「代码改到哪了」的记忆只剩一句概括。</>,
          en: <><Strong>The trigger ignores the task.</Strong> The threshold is pure token arithmetic; it does not know where the work stands. For assistant-style agents, a window can hold several interleaved topics, and a mechanical compaction blends them together. For coding agents, the compaction often lands halfway through a phase, say after three files are edited and before the tests run. Afterwards, what the model remembers about “where the code changes stand” is one sentence.</>,
        })}</Li>
        <Li>{t({
          zh: <><Strong>平均上下文冗长。</Strong>压缩只在窗口快满时才触发，也就是说在绝大部分时间里，模型都在一个冗长、混杂的上下文里工作。这会稀释模型的注意力，无关的历史消息也容易带偏当前判断，也就是常说的 context rot。</>,
          en: <><Strong>The context is long on average.</Strong> Compaction only fires when the window is nearly full, so most of the time the model works inside a long, mixed context. That dilutes attention, and unrelated history pulls the current judgment off course, the effect often called context rot.</>,
        })}</Li>
      </Ol>

      <P>{t({
        zh: <>三个问题的根源是同一个：<Strong>整个对话的唯一副本绑定在模型的上下文里</Strong>。既然是孤本，压缩必然丢信息，触发时机只能向 token 容量妥协，压缩前的上下文也只能越攒越长。</>,
        en: <>All three come from one root cause: <Strong>the only copy of the conversation lives inside the model’s context</Strong>. Because it is the only copy, compaction has to lose something, the trigger has to yield to token capacity, and the context has to keep growing until then.</>,
      })}</P>

      <TimelineCompare t={t} />

      <H2>{t({ zh: 'OpenViking 之前走的路：把对话的主副本挪到模型外面', en: 'The road OpenViking took earlier: move the primary copy out of the model' })}</H2>

      <P>{t({
        zh: <>几个月前，我们在 VikingBot 和 <A href={t(OPENCLAW_DOC)}>OpenClaw</A> 的实践里走了另一条路：不再把对话的主副本放在模型上下文里，而是持续追加写入 OpenViking 的 session。模型看到的窗口由 OpenViking 动态组装：远期历史提炼成摘要，窗口里只保留较短、与当前任务相关的活跃消息；模型需要细节时调用工具，就能把归档的完整原文取回来。这就是 OpenViking 一直讲的<A href={CONTEXT_DB_POST}>「Data in, Context out」</A>：数据完整存入，模型每一轮拿到的是按需组装的上下文。</>,
        en: <>A few months ago, our work on VikingBot and <A href={t(OPENCLAW_DOC)}>OpenClaw</A> took a different route: instead of keeping the primary copy of the conversation in the model’s context, every message is appended to an OpenViking session. The window the model sees is assembled by OpenViking: distant history is condensed into a summary, only the short, task-relevant active messages stay in the window, and when the model needs a detail it calls a tool and gets the archived original back. This is what OpenViking calls <A href={CONTEXT_DB_POST}>“Data in, Context out”</A>: the data goes in complete, and each turn the model receives a context assembled on demand.</>,
      })}</P>

      <P>{t({
        zh: <>具体到 OpenClaw 插件，模型每一轮看到的不再是无限膨胀的原始记录，而是「压缩后的历史摘要 + 归档索引 + 活跃消息」。会话消息源源不断地追加进 OpenViking 的 session，一旦待归档的 token 数达到模型窗口的设定比例，就触发 commit：服务端把这批消息归档落盘，并在后台生成对应片段的 Working Memory 和长期记忆。模型端有 <InlineCode>ov_archive_search</InlineCode> 和 <InlineCode>ov_archive_expand</InlineCode> 两个工具，可以按关键词搜索归档，也可以把某段归档还原成原始消息。VikingBot 是同一套逻辑：session 上下文始终带着最新归档的 overview，commit 由预设的消息阈值自动触发。</>,
        en: <>In the OpenClaw plugin, what the model sees each turn is “a condensed history summary + an archive index + the active messages”, not an ever-growing raw transcript. Messages stream into the OpenViking session, and once the tokens waiting to be archived reach a configured share of the model’s window, a commit fires: the server archives that batch to disk and generates a Working Memory and long-term memories for it in the background. On the model side, two tools, <InlineCode>ov_archive_search</InlineCode> and <InlineCode>ov_archive_expand</InlineCode>, search the archive by keyword and expand a segment back into its original messages. VikingBot follows the same logic: the session context always carries the overview of the latest archive, and commits are triggered automatically by a message threshold.</>,
      })}</P>

      <P>{t({
        zh: <>这套机制解决了「信息有损」和「上下文冗长」：归档是完整的，随时可以取回；上下文压力也被压在低位。但触发仍然是规则驱动的，翻页时机不合理的问题没有根治。在团队内部的 <A href={SWARM_POST}>Agent Swarm</A> 场景里，我们往前走了半步：主 Agent 给子 Agent 派任务时，会先判断要不要让子 Agent 压缩一次上下文。决策权交给了 Agent，只是做判断的还不是真正干活的那个。</>,
        en: <>This fixed information loss and the long average context: the archive is complete and can be recalled at any time, and context pressure stays low. But the trigger was still rule-driven, so the problem of badly timed page turns remained. In our internal <A href={SWARM_POST}>Agent Swarm</A> setup we went half a step further: when the lead agent delegates a task, it decides whether the sub-agent should compact its context first. The decision belongs to an agent, just not the one doing the work.</>,
      })}</P>

      <P>{t({
        zh: '模型的基础环境也变了。那时 256K 窗口还是主流，现在 1M 窗口已经普及，开发者习惯在超长上下文里工作，调用 compact 的频率大幅下降。正因为压缩变少了，每一次触发的时机才更关键：一个长线的助手会话里往往交织着七八件不相关的任务，用户几乎从不主动关心何时该翻页。如果还死守阈值触发，压缩就更容易拦腰截断某个正在进行的任务，而如果在这个任务开始前就翻页，本可以为它腾出一整个干净的窗口。',
        en: 'The models changed too. Back then 256K windows were the norm; now 1M windows are common, developers are used to working in very long contexts, and compaction happens far less often. Precisely because it is rarer, when it happens matters more. A long assistant session tends to interleave seven or eight unrelated tasks, and the user almost never thinks about when to turn the page. With a threshold trigger, compaction is more likely to cut a task in half, when a reset before the task began would have given it a whole clean window.',
      })}</P>

      <P>{t({
        zh: 'Codex 的新机制正好补上这一环：让真正干活的 Agent 自己判断。我们手里已经有了那份独立于模型之外的完整数据副本，剩下的只是把「何时翻页」交给模型。基于这个想法，我们做了一个实验。',
        en: 'Codex’s new mechanism closes exactly that gap: the agent doing the work makes the call. We already had the complete copy of the data outside the model; what remained was handing “when to turn the page” to the model. So we ran an experiment.',
      })}</P>

      <H2>{t({ zh: '实验：Pi + Doubao Seed 2.1 Pro + OpenViking', en: 'The experiment: Pi + Doubao Seed 2.1 Pro + OpenViking' })}</H2>

      <Ul>
        <Li>{t({
          zh: <><Strong>Harness 选 <A href={PI_REPO}>Pi</A></Strong>（<InlineCode>@earendil-works/pi-coding-agent</InlineCode>）。它的扩展 API 很轻：既能注册工具，也允许在每次请求发往模型前拦截并改写整份消息列表，做这类实验最顺手。</>,
          en: <><Strong>The harness is <A href={PI_REPO}>Pi</A></Strong> (<InlineCode>@earendil-works/pi-coding-agent</InlineCode>). Its extension API is light: you can register tools, and you can intercept and rewrite the entire message list before each request goes to the model, which is exactly what this experiment needs.</>,
        })}</Li>
        <Li>{t({
          zh: <><Strong>模型选 Doubao Seed 2.1 Pro</Strong>（火山方舟的 <InlineCode>doubao-seed-2-1-pro-260628</InlineCode>，<InlineCode>reasoning_effort: high</InlineCode>）。这个模型从没针对「自主管理上下文」做过训练。只靠工具定义和提示词，它能不能把这件事做好？这是实验想回答的问题之一。</>,
          en: <><Strong>The model is Doubao Seed 2.1 Pro</Strong> (<InlineCode>doubao-seed-2-1-pro-260628</InlineCode> on Volcengine Ark, with <InlineCode>reasoning_effort: high</InlineCode>). It has never been trained to manage its own context. Can it do the job with nothing but tool definitions and prompts? That is one of the questions the experiment asks.</>,
        })}</Li>
        <Li>{t({
          zh: <><Strong>OpenViking 服务端代码一行不改。</Strong>归档、Working Memory 生成、归档检索，全部复用现有接口。Codex 为这个功能专门搭了 notes 和 history 两个后端；而 OpenViking 现成的 session 归档，天然就是一个 history 后端。</>,
          en: <><Strong>Not a line of OpenViking’s server changes.</Strong> Archiving, Working Memory generation, and archive search all reuse existing endpoints. Codex built two dedicated backends, notes and history, for this feature; OpenViking’s existing session archive already is a history backend.</>,
        })}</Li>
        <Li>{t({
          zh: <>整个实验封装成一个独立的 Pi 扩展，与<A href={t(PI_DOC)}>现有的 OpenViking Pi 扩展</A>并行，互不干扰。</>,
          en: <>The whole experiment is a standalone Pi extension that lives alongside <A href={t(PI_DOC)}>the existing OpenViking Pi extension</A> without touching it.</>,
        })}</Li>
      </Ul>

      <H3>{t({ zh: '模型手里的三个工具', en: 'Three tools in the model’s hands' })}</H3>

      <Table
        headers={[t({ zh: '工具', en: 'Tool' }), t({ zh: '参数', en: 'Parameters' }), t({ zh: '作用', en: 'What it does' })]}
        rows={[
          [
            <InlineCode key="n">new_context</InlineCode>,
            t({ zh: <><InlineCode>reason</InlineCode>、<InlineCode>notes</InlineCode>、<InlineCode>next_steps?</InlineCode></>, en: <><InlineCode>reason</InlineCode>, <InlineCode>notes</InlineCode>, <InlineCode>next_steps?</InlineCode></> }),
            t({ zh: <>归档当前窗口，在新窗口里继续。<InlineCode>notes</InlineCode> 是写给下一个窗口的交接笔记。</>, en: <>Archives the current window and continues in a fresh one. <InlineCode>notes</InlineCode> is the handoff written for the next window.</> }),
          ],
          [
            <InlineCode key="h">history</InlineCode>,
            <><InlineCode>action</InlineCode> ∈ list_windows / list_items / read_item / search_contents</>,
            t({ zh: '回读已归档的窗口：列窗口、列某个窗口的条目、读一条、全文搜索。', en: 'Reads archived windows: list windows, list the items of one window, read one item, full-text search.' }),
          ],
          [
            <InlineCode key="g">get_context_remaining</InlineCode>,
            t({ zh: '无', en: 'none' }),
            t({ zh: '还剩多少 token、当前窗口开了多久、跑了几轮、距用户上一条消息多久，以及一行建议。', en: 'Tokens left, how long the window has been open, how many turns it has run, how long since the user’s last message, and one line of advice.' }),
          ],
        ]}
      />

      <P>{t({
        zh: <>这里和 Codex 有一处明显不同：Codex 的 <InlineCode>new_context</InlineCode> 无参，因为笔记早已写进它专属的 notes 后端；我们没有单独的 notes 工具，所以要求模型在换窗时把 reason 和 notes 作为参数一并传入。这个设计带来一个额外的好处：每次换窗都原样保留了模型自己给出的理由，后面调试和复盘时很有用。</>,
        en: <>One clear difference from Codex: its <InlineCode>new_context</InlineCode> takes no parameters because the notes are already in the dedicated notes backend. We have no separate notes tool, so the model passes reason and notes with the call. That came with a side benefit: every reset preserves, verbatim, the reason the model gave, which turned out to be very useful when debugging and reviewing runs.</>,
      })}</P>

      <H3>{t({ zh: '模型看到的信号', en: 'The signals the model sees' })}</H3>

      <P>{t({
        zh: '模型要做出合理的决策，前提是能感知到当前的上下文压力。我们给它三种信号。',
        en: 'To decide well, the model has to feel the pressure on its context. We give it three signals.',
      })}</P>

      <P>{t({
        zh: <><Strong>常驻指导。</Strong>这段文字附在 system prompt 末尾，整个 session 不变。核心是告诉模型：「你要对自己的上下文窗口负责，系统不会在你背后偷偷压缩对话。」它写明了何时该开新窗口（一个阶段的工作结束、用户切到无关话题、长时间空闲后带着新需求回来、状态行或 <InlineCode>get_context_remaining</InlineCode> 提示空间不足），也写明了何时不该（正处在一串还没验证的代码修改中间、刚刚重置过、或者只是想借翻页逃开一个没解决的问题）。最后要求模型换窗前把笔记写完整，到了新窗口先读窗口头，再用 <InlineCode>history</InlineCode> 补缺，绝不能让用户重复已经归档的内容。</>,
        en: <><Strong>Standing guidance.</Strong> Appended to the end of the system prompt and unchanged for the whole session. Its core message: “You manage your own context window in this session; nothing is summarized behind your back.” It spells out when to open a new window (a phase of the work is finished, the user switches to an unrelated topic, the user comes back after a long idle gap with something new, the status line or <InlineCode>get_context_remaining</InlineCode> says the window is filling up) and when not to (in the middle of an unverified edit sequence, right after a reset, or just to get away from a problem that is not solved). Finally it asks the model to write complete notes before resetting, to read the window header first in the new window and use <InlineCode>history</InlineCode> for whatever it does not cover, and never to ask the user to repeat something an archived window already holds.</>,
      })}</P>

      <P>{t({
        zh: <><Strong>动态状态提示。</Strong>每条用户消息的末尾附一行状态，例如：</>,
        en: <><Strong>A status line.</Strong> Appended after every user message, for example:</>,
      })}</P>

      <div className="amcw-plain">
        <Pre lang="text" lineNumbers={false}>{'[context-status] window w3 · 45 turns · ~57.5k/128k tokens (45%) · 35s since your previous message'}</Pre>
      </div>

      <P>{t({
        zh: '如果系统空闲超过 30 分钟才收到新消息，这一行后面还会加一句：「如果这个请求是一项全新的工作，请考虑先开一个新窗口。」',
        en: 'If a new message arrives after more than 30 minutes of idle time, one more line is added: “If this request starts unrelated work, consider new_context before you begin.”',
      })}</P>

      <P>{t({
        zh: <><Strong>阈值提醒。</Strong>每个窗口最多触发一次软提醒和一次硬提醒。越过软阈值时，系统提示「收尾或做好检查点，然后带着完整的笔记调用 new_context」；触及硬阈值时，措辞变成「现在就调用。再拖下去 harness 就会替你压缩，你的笔记就写不成了」。</>,
        en: <><Strong>Threshold reminders.</Strong> Each window gets at most one soft and one hard reminder. Past the soft threshold: “finish or checkpoint the step you are on, then call new_context with complete notes.” Past the hard threshold the wording tightens: “call it now; if the window overflows first, the harness compacts it for you and your notes are never written.”</>,
      })}</P>

      <H3>{t({ zh: '换窗之后，一段上下文由什么组成', en: 'What a context is made of after a reset' })}</H3>

      <P>{t({
        zh: <>模型调用 <InlineCode>new_context</InlineCode> 后，扩展会把当前窗口内的所有消息推送到 OpenViking 的 session，在末尾缀上一条由 reason 和 notes 拼成的交接消息，然后发起 commit。OpenViking 同步把这段归档落盘，并在后台生成配套的 Working Memory。<Strong>归档成功落盘是换窗的硬性前提</Strong>：OpenViking 不可达或 commit 失败，系统就拒绝切割，模型只能在原窗口继续。归档完成后，模型看到的消息列表就变成下图左边的结构。</>,
        en: <>When the model calls <InlineCode>new_context</InlineCode>, the extension pushes every message of the current window to the OpenViking session, appends a handoff message built from the reason and the notes, and commits. OpenViking writes the archive to disk and generates a Working Memory for it in the background. <Strong>A successful archive is a hard precondition for the reset</Strong>: if OpenViking is unreachable or the commit fails, nothing is cut and the model keeps working in the current window. Once the archive is in place, the message list the model sees takes the shape on the left of the figure below.</>,
      })}</P>

      <WindowAnatomy t={t} />

      <P>{t({
        zh: <>上一个窗口从活跃列表里消失了，但并没有真正消失。OpenViking 服务端上，这个 session 的目录完整记录着一切（图右）。三层文件对应 OpenViking 的三级加载：<InlineCode>history list_windows</InlineCode> 只返回轻量的 abstract；新窗口头只装 overview；只有模型显式调用 <InlineCode>history read_item</InlineCode> 和 <InlineCode>search_contents</InlineCode> 时，系统才去读完整原文。模型每一轮的上下文里始终只带着 overview 这一层，海量原文留在 OpenViking 里，随时可以按需取回。</>,
        en: <>The previous window is gone from the active list, but it has not gone away. On the OpenViking server, the session’s directory (right side of the figure) records all of it. The three files map to OpenViking’s three loading levels: <InlineCode>history list_windows</InlineCode> returns only the lightweight abstract; the new window header loads only the overview; the full transcript is touched only when the model explicitly calls <InlineCode>history read_item</InlineCode> or <InlineCode>search_contents</InlineCode>. Every turn, the model’s context carries just the overview layer, while the bulk of the raw text stays in OpenViking, ready to be pulled on demand.</>,
      })}</P>

      <P>{t({
        zh: '整个过程里，磁盘上 Pi 的原始 session 文件一条都没删，变的只是发往模型的那份消息列表。在一个 turn 内，工具批次执行完毕后的下一次采样，就已经在新窗口里了。这种在后台完成切换的做法，和 Codex 的语义一致。',
        en: 'Throughout, not a single entry of Pi’s session file on disk is deleted; only the message list sent to the model changes. Within a turn, the very next sampling after the tool batch completes is already in the new window. Doing the switch in the background like this matches Codex’s semantics.',
      })}</P>

      <H3>{t({ zh: '窗口头长什么样', en: 'What the window header looks like' })}</H3>

      <P>{t({
        zh: '下面截取自一次长线任务首次换窗后，模型看到的真实窗口头。内容做了删节，结构完整保留：',
        en: 'Below is the real window header the model saw after the first reset of a long task, trimmed for length with the structure intact:',
      })}</P>

      <div className="amcw-plain">
        <Pre lang="text" filename="window header · w2" lineNumbers={false}>{WINDOW_HEADER}</Pre>
      </div>

      <P>{t({
        zh: <>这里有两份「摘要」并存，视角不同：<InlineCode>handoff-notes</InlineCode> 出自干活的模型，是它换窗前写的交接笔记；<InlineCode>working-memory</InlineCode> 由 OpenViking 服务端拿着包含所有工具输出的完整归档生成，是七段式的工作记忆。前者写的是模型「主观上打算做什么」，后者记录的是「实际上发生过什么」。比如上面 Errors &amp; Corrections 里的两次报错，模型自己的笔记里一个字都没提。</>,
        en: <>Two “summaries” coexist here, from two viewpoints. <InlineCode>handoff-notes</InlineCode> comes from the working model: the notes it wrote before resetting. <InlineCode>working-memory</InlineCode> is generated by the OpenViking server from the complete archive, tool output included, in seven sections. The first says what the model intended to do; the second records what actually happened. The two errors under Errors &amp; Corrections above, for instance, never appear in the model’s own notes.</>,
      })}</P>

      <H3>{t({ zh: 'OpenViking 在这里承担了什么', en: 'What OpenViking carries here' })}</H3>

      <P>{t({
        zh: '拆开来看，模型端只负责两件事：决定何时翻页，写一段交接笔记。剩下的都由 OpenViking 承担：',
        en: 'Taken apart, the model side does only two things: decide when to turn the page, and write the handoff notes. OpenViking does the rest:',
      })}</P>

      <Ul>
        <Li>{t({
          zh: <><Strong>无损归档。</Strong>每个窗口的全部消息，尤其是长篇的工具输出，都原样进入 <InlineCode>messages.jsonl</InlineCode>。换窗不是压缩，而是把数据的主副本从模型上下文转移到数据库。「信息有损」从根源上消失了。</>,
          en: <><Strong>Lossless archive.</Strong> Every message in a window, above all the long tool output, goes into <InlineCode>messages.jsonl</InlineCode> as is. A reset is not compaction; it moves the primary copy of the data from the model’s context into the database. Information loss disappears at the root.</>,
        })}</Li>
        <Li>{t({
          zh: <><Strong>摘要由服务端生成。</Strong>Working Memory 由 OpenViking 在后台用自己的模型、基于完整归档生成，不占干活模型的上下文，不消耗它的注意力，也不会因为窗口告急而写得敷衍。Codex 放弃了客观摘要，把宝押在模型主观写的 notes 上；我们把两者叠加，模型负责表达意图，服务端负责记录事实。</>,
          en: <><Strong>The summary is written server-side.</Strong> OpenViking generates the Working Memory in the background with its own model, from the complete archive. It takes no room in the working model’s context, consumes none of its attention, and is never rushed because the window is running out. Codex dropped the objective summary and bet everything on the model’s subjective notes; we stack the two: the model states its intent, the server records the facts.</>,
        })}</Li>
        <Li>{t({
          zh: <><Strong>分层读取。</Strong>abstract、overview、原文三级结构是 OpenViking 现成的。窗口头只装 overview，控制住每个新窗口的起始大小；模型要抠某个细节时，一次 <InlineCode>history</InlineCode> 调用就能拿到完整原文，不需要用户再解释历史。</>,
          en: <><Strong>Layered reads.</Strong> The abstract / overview / raw-text ladder already exists in OpenViking. The window header carries only the overview, which keeps every new window small at the start; when the model needs a specific detail, one <InlineCode>history</InlineCode> call returns the original text, and the user never has to re-explain the past.</>,
        })}</Li>
        <Li>{t({
          zh: <><Strong>全局可检索。</Strong>模型的 <InlineCode>history search_contents</InlineCode> 直接落到 OpenViking 的 <InlineCode>search/grep</InlineCode> 接口，跨所有归档做全文检索。</>,
          en: <><Strong>Searchable everywhere.</Strong> The model’s <InlineCode>history search_contents</InlineCode> maps straight onto OpenViking’s <InlineCode>search/grep</InlineCode> endpoint, a full-text search across every archive.</>,
        })}</Li>
        <Li>{t({
          zh: <><Strong>跨 session 的长期记忆。</Strong>这是 Codex 的 notes/history 后端没有的。OpenViking 的 commit 除了归档和生成 Working Memory，还会跑一遍记忆抽取，把用户偏好、事实和经验写进 <InlineCode>viking://user/...</InlineCode> 下的长期记忆。下一个 session、下一个 Agent，甚至挂在另一个 harness 上的 Agent，都能通过 auto-recall 拿到。换窗留下的沉淀不再只服务当前这一个任务。</>,
          en: <><Strong>Long-term memory across sessions.</Strong> This is something Codex’s notes/history backends do not have. Besides archiving and generating the Working Memory, an OpenViking commit also runs memory extraction and writes user preferences, facts, and experience into long-term memory under <InlineCode>viking://user/...</InlineCode>. The next session, the next agent, even an agent running on a different harness, can recall them through auto-recall. What a reset leaves behind no longer serves only the current task.</>,
        })}</Li>
        <Li>{t({
          zh: <><Strong>一个后端，多种 harness。</Strong>本次实验依赖的 session、commit、归档落盘和 grep 接口，与 OpenClaw 插件、VikingBot、Claude Code 记忆插件用的完全是同一套。服务端不需要为「Agent 自主换窗」加任何逻辑分支。这个新模式只是 OpenViking 现有基础设施的又一种用法。</>,
          en: <><Strong>One backend, many harnesses.</Strong> The session, commit, archive, and grep endpoints this experiment relies on are the same ones the OpenClaw plugin, VikingBot, and the Claude Code memory plugin use. The server needed no new code path for “agent-managed windows”. The new mode is just another way to use the infrastructure OpenViking already has.</>,
        })}</Li>
      </Ul>

      <H3>{t({ zh: '和 Codex 的对照', en: 'Side by side with Codex' })}</H3>

      <Table
        headers={['Codex', t({ zh: '这个实验', en: 'This experiment' })]}
        rows={[
          [
            <>history {t({ zh: '后端', en: 'backend' })} <InlineCode>alpha/history/v2</InlineCode></>,
            t({ zh: <>OpenViking session 的消息流，每个窗口归档到 <InlineCode>history/archive_NNN/messages.jsonl</InlineCode></>, en: <>The OpenViking session’s message stream, each window archived to <InlineCode>history/archive_NNN/messages.jsonl</InlineCode></> }),
          ],
          [
            <>notes {t({ zh: '后端', en: 'backend' })} <InlineCode>alpha/notes/v2</InlineCode></>,
            t({ zh: <><InlineCode>new_context</InlineCode> 的 <InlineCode>notes</InlineCode> 参数</>, en: <>The <InlineCode>notes</InlineCode> parameter of <InlineCode>new_context</InlineCode></> }),
          ],
          [
            <><InlineCode>{'<context_window>'}</InlineCode> {t({ zh: '里的', en: 'carries a' })} <InlineCode>thread_hint</InlineCode></>,
            t({ zh: 'OpenViking 生成的 Working Memory + 模型自己的交接笔记', en: 'The Working Memory generated by OpenViking + the model’s own handoff notes' }),
          ],
          [
            <><InlineCode>history.list_windows / list_items / read_item / search_contents</InlineCode></>,
            t({ zh: <>同名 action，分别落到 <InlineCode>fs/ls</InlineCode>、<InlineCode>content/read messages.jsonl</InlineCode>、<InlineCode>search/grep</InlineCode></>, en: <>Same action names, mapped to <InlineCode>fs/ls</InlineCode>, <InlineCode>content/read messages.jsonl</InlineCode>, and <InlineCode>search/grep</InlineCode></> }),
          ],
          [
            <><InlineCode>new_context</InlineCode>{t({ zh: '（无参数）', en: ' (no parameters)' })}</>,
            <InlineCode key="nc">new_context(reason, notes, next_steps?)</InlineCode>,
          ],
          [
            <><InlineCode>get_context_remaining</InlineCode> → <InlineCode>{'{tokens_left}'}</InlineCode></>,
            t({ zh: '剩余 token 之外，还给窗口时长、轮数、空闲间隔、归档状态和一行建议', en: 'Tokens left plus window age, turn count, idle gap, archive readiness, and one line of advice' }),
          ],
          [
            t({ zh: '采样结束后原生重建窗口', en: 'Native window rebuild after sampling' }),
            t({ zh: <>Pi <InlineCode>context</InlineCode> 钩子里的虚拟切割</>, en: <>A virtual cut in Pi’s <InlineCode>context</InlineCode> hook</> }),
          ],
          [
            t({ zh: 'guidance / reminder / fallback 三段提示词', en: 'Three prompts: guidance / reminder / fallback' }),
            t({ zh: '常驻指导 / 软硬提醒 / Pi 压缩兜底', en: 'Standing guidance / soft and hard reminders / Pi’s compaction as the fallback' }),
          ],
          [
            t({ zh: '无长期记忆', en: 'No long-term memory' }),
            t({ zh: 'commit 同时抽取长期记忆，跨 session、跨 Agent 可用', en: 'The commit also extracts long-term memory, usable across sessions and agents' }),
          ],
        ]}
      />

      <H2>{t({ zh: '跑一个一个窗口装不下的任务', en: 'Running a task that does not fit in one window' })}</H2>

      <P>{t({
        zh: '短的验收脚本能验证代码逻辑走得通，却验不出模型在压力下会不会真的做出决策。所以我们给它准备了一个注定在一个窗口内做不完的任务：',
        en: 'A short acceptance script proves the code path works, but it says nothing about whether the model will actually make decisions under pressure. So we set up a task that cannot possibly fit in one window:',
      })}</P>

      <Ul>
        <Li>{t({
          zh: '把这个扩展自身的 22 个源文件（共 411 KB，全部读完约 105k token）放进一个空白项目；',
          en: 'Put the extension’s own 22 source files (411 KB, about 105k tokens if read in full) into an empty project.',
        })}</Li>
        <Li>{t({
          zh: '告诉 Pi 模型的上下文窗口只有 128k，并把软提醒阈值压到 45%，让整个换窗过程能在一次演示里完整复现；',
          en: 'Tell Pi the model’s context window is 128k, and lower the soft reminder threshold to 45%, so the whole reset cycle plays out within one demo.',
        })}</Li>
        <Li>{t({
          zh: <>要求模型按 <InlineCode>TASK.md</InlineCode> 里的清单顺序逐个读文件，每读完一个，就向 <InlineCode>INVENTORY.md</InlineCode> 追加一条记录（职责、主要导出、风险），并在 <InlineCode>TASK.md</InlineCode> 里打勾；不许对没读过的文件凭空总结；</>,
          en: <>Ask the model to work through the files in the order listed in <InlineCode>TASK.md</InlineCode>, and after each one append an entry to <InlineCode>INVENTORY.md</InlineCode> (responsibility, main exports, risks) and tick it off in <InlineCode>TASK.md</InlineCode>. It must not summarize files it has not read.</>,
        })}</Li>
        <Li>{t({
          zh: <><Strong>任务描述里不提任何「上下文管理」的字眼。</Strong>模型能依靠的只有常驻指导、一行状态提示和三个工具。</>,
          en: <><Strong>The task description never mentions context management.</Strong> All the model has to go on are the standing guidance, the status line, and the three tools.</>,
        })}</Li>
      </Ul>

      <P>{t({ zh: '结果如下：', en: 'Here is how it went:' })}</P>

      <StatStrip t={t} />

      <PressureChart t={t} />

      <H3>{t({ zh: '三次换窗，两种理由', en: 'Three resets, two kinds of reason' })}</H3>

      <P>{t({
        zh: '前两次换窗是压力驱动的。模型在 reason 里准确写出了当时的占用比例和任务进度：',
        en: 'The first two resets were pressure-driven. In its reason, the model named the current usage and where the task stood:',
      })}</P>

      <Quote>{REASONS[0]}</Quote>
      <Quote>{REASONS[1]}</Quote>

      <P>{t({
        zh: '第三次不一样：当时没有任何提醒触发。22 个文件全部盘点完之后，用户追问了一个关于第一个文件的细节。模型答完，判断这个阶段的任务已经结束，主动换窗：',
        en: 'The third was different: no reminder had fired. After all 22 files were inventoried, the user asked a follow-up about the first file. The model answered, judged that this phase of work was over, and reset on its own:',
      })}</P>

      <Quote>{REASONS[2]}</Quote>

      <P>{t({
        zh: '在任务边界上翻页，正是阈值压缩做不到的事。它保证下一项工作能在一个干净的窗口里开始。',
        en: 'Turning the page at a task boundary is exactly what threshold compaction cannot do. It guarantees the next piece of work starts in a clean window.',
      })}</P>

      <P>{t({
        zh: <>还有一个细节：w3 进行到 32% 时，模型主动调用了一次 <InlineCode>get_context_remaining</InlineCode>，收到「no action needed」的建议后继续工作。它既没有一看到压力就换窗，也没有对空间视而不见。</>,
        en: <>One more detail: at 32% into w3, the model called <InlineCode>get_context_remaining</InlineCode> on its own, got the advice “no action needed”, and went back to work. It neither reset at the first sign of pressure nor ignored the space it had left.</>,
      })}</P>

      <P>{t({
        zh: <>三次换窗下来，模型的上下文里自始至终没有出现过一句「压缩版对话」。三段完整的归档留在 OpenViking 里，每一段都带着自己的 Working Memory，等着 <InlineCode>history</InlineCode> 来读。</>,
        en: <>Across three resets, not one line of “compacted conversation” ever entered the model’s context. Three complete archives sit in OpenViking, each with its own Working Memory, waiting for <InlineCode>history</InlineCode> to read them.</>,
      })}</P>

      <P>{t({
        zh: '我们还把窗口管理关掉、交给 Pi 自己的阈值压缩，用同一个模型把同一个任务再跑了一轮：两轮都做到 22/22，阈值压缩那轮发出的 prompt token 多出约三分之一（452 万对 331 万，按缓存折价算只差一成），但峰值占用冲到了 97%，而自主换窗那轮是 47%，并且在压缩生效前它先废掉了一次 12.5 万 token 的请求，那次请求只换回 1 个 token。',
        en: 'We also ran the same task with the same model once more with window management switched off, leaving compaction to Pi’s own threshold: both runs finished 22 of 22, the compaction run sent about a third more prompt tokens (4.52M against 3.31M, a gap that shrinks to about a tenth once cache discounts are applied), but its context peaked at 97% against 47% for the agent-managed run, and before compaction kicked in it burned one 125k-token request that returned a single token.',
      })}</P>

      <H2>{t({ zh: '我们从这次实验里看到了什么', en: 'What we learned' })}</H2>

      <P>{t({
        zh: <><Strong>把上下文的控制权交给模型是可行的，即便它没受过相关训练。</Strong>Doubao Seed 2.1 Pro 第一次见到这三个工具，仅凭一段常驻指导、一行状态反馈和一次软提醒，就在三次换窗里给出了合理的理由和可用的笔记，还在没有提醒的情况下自己找到了任务边界。这说明 Codex 那套机制的核心，是「给模型压力信号，并给它一条没有后顾之忧的退路」。模型层面的专门训练能提升稳定性，但不是前提。</>,
        en: <><Strong>Handing control of the context to the model works, even without training for it.</Strong> Doubao Seed 2.1 Pro had never seen these three tools. With one standing guidance block, one status line, and one soft reminder, it gave sound reasons and usable notes at all three resets, and found a task boundary on its own with no reminder at all. The core of the Codex mechanism, then, is “give the model pressure signals and a safe way out”. Dedicated training on the model side can make it more consistent, but it is not a prerequisite.</>,
      })}</P>

      <P>{t({
        zh: <><Strong>退路完备，模型才有翻页的底气。</Strong>阈值压缩的死穴是「一旦压缩，覆水难收」，所以系统只能拖到最后一刻。有了完整归档，翻页的代价降成了「多调一次 <InlineCode>history</InlineCode>」。正因如此，模型才敢在只用了 45% 时换窗，才敢在任务边界上果断翻页。「何时翻页」这个决策的质量，取决于翻页之后系统给它留了多宽的退路。在这一点上，OpenViking 扮演的角色和 Codex 的 history 后端相同，只是顺手把摘要生成、全局检索和长期记忆也一并包了。</>,
        en: <><Strong>With a complete way back, the model can afford to turn the page.</Strong> The fatal flaw of threshold compaction is that once you compact, there is no undo, so the system waits until the last moment. With a complete archive, the cost of a reset drops to “one more <InlineCode>history</InlineCode> call”. That is why the model was willing to reset at 45% and to turn the page decisively at a task boundary. The quality of the “when to reset” decision depends on how wide a way back the system leaves afterwards. Here OpenViking plays the same role as Codex’s history backend, and takes care of summary generation, global search, and long-term memory along the way.</>,
      })}</P>

      <P>{t({
        zh: <><Strong>摘要该由谁来写，是个真问题。</Strong>阈值压缩让一个已经快塞满的模型在注意力被稀释的状态下挤出摘要。这套机制做了分工：模型只写它最清楚的部分（主观目标、关键决策、下一步计划），客观的历史记录交给外部系统。服务端在后台拿着包含所有工具输出的完整原文生成 Working Memory。主客观两份记录并存，比任何单一视角的总结都可靠。</>,
        en: <><Strong>Who writes the summary is a real question.</Strong> Threshold compaction asks a model whose window is nearly full, with its attention already diluted, to squeeze out a summary. This mechanism splits the job: the model writes only what it knows best (its goals, key decisions, next steps), and the objective record is left to an external system, which generates the Working Memory in the background from the full transcript, tool output included. Two records, subjective and objective, side by side are more reliable than any single-viewpoint summary.</>,
      })}</P>

      <P>{t({
        zh: <><Strong>显性的代价主要是等待。</Strong>目前每次换窗会阻塞 50 到 90 秒，等 Working Memory 生成完。这段时间其实可以抹平：commit 一成功就开新窗口，让模型先带着自己的笔记继续，Working Memory 生成好之后再补到窗口头。「等不到就先开窗、后续再补读」的降级路径已经存在，只是现在只在超时时才启用。要把它变成默认行为，就得把 commit 从换窗的关键路径上拆出去。这次演示故意保留阻塞式设计，是为了让「换窗那一刻就拿到完整摘要」在观感上更直接。Codex 和 Claude Code 目前在这一步也都是阻塞的。</>,
        en: <><Strong>The visible cost is mostly waiting.</Strong> Right now each reset blocks for 50 to 90 seconds while the Working Memory is generated. That wait can be removed: open the new window as soon as the commit succeeds, let the model carry on with its own notes, and fill the Working Memory into the header once it is ready. The fallback of “open the window anyway and read the summary later” already exists; it just only activates on timeout today. Making it the default means taking the commit off the reset’s critical path. This demo keeps the blocking design on purpose, so that “the full summary is there the moment the window opens” is easy to see. Codex and Claude Code block at this step today as well.</>,
      })}</P>

      <P>{t({
        zh: <><Strong>已知的局限。</Strong>Pi 只在模型每次回复后才拿到精确的 token 计数，之后追加的消息只能按字符数估算，所以状态行里的压力数字带有估算成分；状态行只在每条用户消息后更新一次，模型陷入长工具调用循环时，看到的数字仍是这个 turn 开始时的，要拿实时数据只能主动调 <InlineCode>get_context_remaining</InlineCode>。另外，notes 一旦进入 OpenViking，就会被纳入全局索引和检索，这和 Codex 那种只有模型自己能读写的私有草稿纸不同。</>,
        en: <><Strong>Known limitations.</Strong> Pi only gets an exact token count after each model reply; messages appended after that are estimated from character counts, so the pressure numbers in the status line are partly estimates. The status line is updated once per user message, so during a long tool loop the model still sees the number from the start of the turn; for a live reading it has to call <InlineCode>get_context_remaining</InlineCode>. And once notes enter OpenViking they are indexed and searchable like everything else, unlike the private scratchpad that only the model can read and write in Codex.</>,
      })}</P>

      <H2>{t({ zh: '这还是个实验', en: 'Still an experiment' })}</H2>

      <P>{t({
        zh: <>实验代码在 OpenViking 仓库的 <A href={EXPERIMENT_DIR}><InlineCode>examples/pi-experimental-context-management/</InlineCode></A> 目录（代码合入后的最终路径）。目录名里的 experimental 是认真的：这是一个用来验证想法的沙盒，不是开箱即用的产品。同级目录的 <InlineCode>demo-evidence/</InlineCode> 归档了这次长任务的全部原始痕迹：每一次请求的报文、模型的每一次工具调用参数、三段归档及其 Working Memory、Pi 的 session 文件和扩展日志（密钥和内网地址已脱敏）。</>,
        en: <>The code is in the OpenViking repository under <A href={EXPERIMENT_DIR}><InlineCode>examples/pi-experimental-context-management/</InlineCode></A> (the final path once merged). The word experimental in the name is meant literally: this is a sandbox for testing an idea, not a product you install and forget. Next to it, <InlineCode>demo-evidence/</InlineCode> keeps the full raw trace of the long run: every request payload, every tool call the model made with its arguments, the three archives and their Working Memories, Pi’s session file, and the extension log, with secrets and internal addresses redacted.</>,
      })}</P>

      <P>{t({ zh: '接下来想做的事：', en: 'What we want to do next:' })}</P>

      <Ul>
        <Li>{t({
          zh: '把阻塞式换窗改成默认异步，把等待时间从换窗的关键路径上拿掉。',
          en: 'Make the asynchronous reset the default and take the wait off the critical path.',
        })}</Li>
        <Li>{t({
          zh: <>增加一个独立的 <InlineCode>notes</InlineCode> 工具，让模型可以边干边记，而不是只能在换窗那一刻写一次笔记。</>,
          en: <>Add a standalone <InlineCode>notes</InlineCode> tool so the model can take notes as it works, instead of writing them once at the moment of reset.</>,
        })}</Li>
        <Li>{t({
          zh: '把「换窗触发权交给模型」接回 VikingBot 和 OpenClaw。它们已经有归档、检索和阈值触发，缺的只是最后这一步。',
          en: 'Bring “the model decides when to reset” back into VikingBot and OpenClaw. They already have archiving, search, and threshold triggers; this is the one missing piece.',
        })}</Li>
        <Li>{t({
          zh: '把对照实验扩大到更多任务和模型，比较「阈值压缩」和「模型自主换窗」的交付质量，把「翻页时机更合理」从直觉变成数据。',
          en: 'Extend the controlled comparison to more tasks and models, threshold compaction against model-managed resets, and turn “better-timed page turns” from an intuition into numbers.',
        })}</Li>
        <Li>{t({
          zh: '压缩 Working Memory 的生成耗时，或者改成更轻量的增量更新。这是目前换窗成本里最大的一项。',
          en: 'Cut the Working Memory generation time, or move to lighter incremental updates. It is the largest item on the reset’s cost sheet today.',
        })}</Li>
      </Ul>

      <P>{t({
        zh: <>如果你也在自己的 harness 上尝试这条路，欢迎来 <A href={OPENVIKING_GITHUB}>OpenViking 仓库</A>交流。</>,
        en: <>If you are trying this on your own harness, come talk to us in the <A href={OPENVIKING_GITHUB}>OpenViking repository</A>.</>,
      })}</P>

      <H2>{t({ zh: '复现', en: 'Reproduce it' })}</H2>

      <Pre lang="bash" filename="terminal" lineNumbers={false}>{REPRO}</Pre>

      <Callout type="info" title={t({ zh: '更多细节', en: 'More detail' })}>
        <P>{t({
          zh: <>交互式演示和全部配置项的说明，见 <A href={EXPERIMENT_DIR}>该目录</A>下的 <InlineCode>README.md</InlineCode> 和 <InlineCode>CONTEXT-WINDOW.md</InlineCode>。</>,
          en: <>The interactive demo and every configuration option are documented in <InlineCode>README.md</InlineCode> and <InlineCode>CONTEXT-WINDOW.md</InlineCode> in <A href={EXPERIMENT_DIR}>the same directory</A>.</>,
        })}</P>
      </Callout>
    </Article>
  );
}

export default {
  id: SLUG,
  Component: AgentManagedContextWindows,
  meta: {
    title: {
      zh: '让 Agent 自己决定何时翻页：用 OpenViking 在 Pi 上复刻 Codex 的实验性上下文管理',
      en: 'Let the Agent Turn the Page: Codex-Style Context Management on Pi, Backed by OpenViking',
    },
    description: {
      zh: 'Codex 把「何时开新窗口」交给了模型。我们在 Pi 上用 OpenViking 现成的 session 归档复刻了这套机制，让一个没受过相关训练的模型跑完了单个窗口装不下的任务。',
      en: 'Codex now lets the model decide when a context window ends. We rebuilt the mechanism on Pi with OpenViking’s existing session archive, and a model with no training for it finished a task larger than one window.',
    },
    cover: COVER,
    cardCover: CARD_COVER,
    publishedAt: '2026-09-11',
    readingTime: { en: 16, zh: 14 },
    category: { zh: '上下文工程', en: 'Context Engineering' },
    tags: ['openviking', 'context', 'codex', 'memory', 'agent'],
    languages: ['en', 'zh'],
    llmPath: LLM_PATH,
    authors: [{ name: 'OpenViking Team', github: 'volcengine' }],
  },
};
