# Copyright (c) 2026 Beijing Volcano Engine Technology Co., Ltd.
# SPDX-License-Identifier: Apache-2.0
"""
Memory operations definitions - final output from LLM.

This module defines the placeholder types for memory operations.
The actual concrete models are dynamically generated by SchemaModelGenerator.
"""

from typing import Any, List, Optional

from pydantic import BaseModel, Field


class StructuredMemoryOperations(BaseModel):
    """
    Final memory operations output from LLM - system executes directly.

    This is a placeholder base class. The actual concrete model with
    type-safe write_uris and edit_uris is dynamically generated by
    SchemaModelGenerator.create_structured_operations_model().
    """

    write_uris: List[Any] = Field(
        default_factory=list,
        description="Write operations with flat data format",
    )
    edit_uris: List[Any] = Field(
        default_factory=list,
        description="Edit operations with flat data format",
    )
    delete_uris: List[str] = Field(
        default_factory=list,
        description="Delete operations as URI strings",
    )

    def is_empty(self) -> bool:
        """Check if there are any operations."""
        return (
            len(self.write_uris) == 0
            and len(self.edit_uris) == 0
            and len(self.delete_uris) == 0
        )


# Backward compatibility alias
MemoryOperations = StructuredMemoryOperations
