name: 17. Docs

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - '.github/workflows/_docs.yml'
      - '.github/workflows/_docs-deploy.yml'
      - '.github/workflows/docs.yml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  docs-deploy:
    name: Build and Deploy Docs
    if: github.repository == 'volcengine/OpenViking'
    uses: ./.github/workflows/_docs-deploy.yml
    permissions:
      contents: read
      pages: write
      id-token: write
