"""Hermes messages and senders to OpenViking message parts and peer IDs."""

from __future__ import annotations

import hashlib
import json
import re
from contextlib import suppress
from typing import Any, Dict, List, Optional

from .host import extract_user_instruction_from_skill_message, flatten_message_text
from .tools import _OPENVIKING_RECALL_TOOL_NAMES

_OPENVIKING_SESSION_PREFIX = "hermes-"


def openviking_session_id(hermes_session_id: Any) -> str:
    """The OpenViking session id for a Hermes session id: ``hermes-<id>``, never prefixed twice.

    Every request that names a session (recall, the search tool, upload, commit) and
    every new pending marker uses this. Markers written by 2.x hold the bare Hermes
    id; recovery commits a marker's stored id as is and never maps it again.
    """
    sid = str(hermes_session_id or "").strip()
    if not sid or sid.startswith(_OPENVIKING_SESSION_PREFIX):
        return sid
    return _OPENVIKING_SESSION_PREFIX + sid


def _gateway_peer_id(platform: str, sender: Any) -> str:
    """Namespace transport IDs and encode path-like IDs without merging distinct senders."""
    platform, sender = str(platform or "").strip().lower(), str(sender or "").strip()
    if not platform or not sender:
        return ""
    raw = f"{platform}.{sender}"
    if len(raw) <= 128 and re.fullmatch(r"[a-zA-Z0-9_.@-]+", raw) and raw.count("@") <= 1:
        return raw
    # Preserve the peer paths generated by the original Hermes #105812.
    safe = re.sub(r"[^a-zA-Z0-9_.@-]+", "-", raw)
    safe = re.sub(r"@+", "-", safe).strip(".-") or "gateway-peer"
    digest = hashlib.sha256(raw.encode("utf-8")).hexdigest()[:12]
    return f"{safe[:128 - len(digest) - 1].rstrip('.-') or 'gateway-peer'}-{digest}"


def _derive_openviking_user_text(content: Any) -> str:
    """Strip Hermes slash-skill scaffolding before sending content to OpenViking
    (MemoryManager already does this for the fan-out; kept for direct hook callers)."""
    return extract_user_instruction_from_skill_message(content) or ""


def _preview(value: Any, limit: int = 160) -> str:
    text = ("" if value is None else str(value)).replace("\n", "\\n")
    return text[:limit] + "..." if len(text) > limit else text


# Inbound tool-result status aliases -> canonical "error" / "completed" (else "pending").
_TOOL_STATUS_ERROR_ALIASES = {"error", "failed", "failure"}
_TOOL_STATUS_COMPLETED_ALIASES = {"completed", "complete", "success", "succeeded"}
_message_text = flatten_message_text  # OpenAI-style string/list content -> text


def _tool_part(tool_id: str, tool_name: str, tool_input: Dict[str, Any], tool_status: str, **extra) -> Dict[str, Any]:
    return {"type": "tool", "tool_id": tool_id, "tool_name": tool_name, "tool_input": tool_input, **extra, "tool_status": tool_status}


def _tool_call_id(tool_call: Dict[str, Any]) -> str:
    return str(tool_call.get("id") or tool_call.get("tool_call_id") or "")


def _tool_call_name(tool_call: Dict[str, Any]) -> str:
    function = tool_call.get("function")
    return str((function.get("name") if isinstance(function, dict) else tool_call.get("name")) or "")


def _is_openviking_recall_tool_name(tool_name: Any) -> bool:
    return str(tool_name or "").strip().lower() in _OPENVIKING_RECALL_TOOL_NAMES


def _tool_call_input(tool_call: Dict[str, Any]) -> Dict[str, Any]:
    function = tool_call.get("function")
    raw_args = function.get("arguments") if isinstance(function, dict) else None
    if raw_args is None:
        raw_args = tool_call.get("args")
    if raw_args is None or (isinstance(raw_args, str) and not raw_args.strip()):
        return {}
    if not isinstance(raw_args, str):
        return raw_args if isinstance(raw_args, dict) else {"value": raw_args}
    with suppress(Exception):
        parsed = json.loads(raw_args)
        return parsed if isinstance(parsed, dict) else {"value": parsed}
    return {"value": raw_args}


def _tool_result_status(message: Dict[str, Any]) -> str:
    raw_status = str(message.get("status") or message.get("tool_status") or "").lower()
    if raw_status in _TOOL_STATUS_ERROR_ALIASES:
        return "error"
    if raw_status in _TOOL_STATUS_COMPLETED_ALIASES:
        return "completed"
    text = _message_text(message.get("content")).strip()
    parsed = None
    if text:
        with suppress(Exception):
            parsed = json.loads(text)
    if isinstance(parsed, dict):
        exit_code = parsed.get("exit_code")
        if (str(parsed.get("status") or "").lower() in _TOOL_STATUS_ERROR_ALIASES or parsed.get("success") is False
                or bool(parsed.get("error")) or (isinstance(exit_code, int) and exit_code != 0)):
            return "error"
    return "completed"


def _rfind_message(messages: List[Any], role: str, start: int, expected: Any = None) -> Optional[int]:
    """Index of the last ``role`` message at or before ``start`` (matching ``expected`` text if given)."""
    expected_text = None if expected is None else _message_text(expected).strip()
    for idx in range(start, -1, -1):
        message = messages[idx]
        if not isinstance(message, dict) or message.get("role") != role:
            continue
        if expected_text is None or (expected_text and _message_text(message.get("content")).strip() == expected_text):
            return idx
    return None


def _index_tool_calls(messages: List[Dict[str, Any]]) -> tuple[Dict[str, Dict[str, Any]], set[str], set[str]]:
    """-> (assistant tool_calls by id, ids with a result in the slice, tool ids to drop).

    Nothing is dropped any more: OpenViking recall-tool results are captured so the
    server can attribute which memories were used. The third value stays for callers.
    """
    tool_calls_by_id: Dict[str, Dict[str, Any]] = {}
    completed_tool_ids: set[str] = set()
    skipped_tool_ids: set[str] = set()
    for message in messages:
        if message.get("role") == "tool":
            if tool_id := str(message.get("tool_call_id") or message.get("id") or ""):
                completed_tool_ids.add(tool_id)
        elif message.get("role") == "assistant":
            for tool_call in message.get("tool_calls") or []:
                if isinstance(tool_call, dict) and (tool_id := _tool_call_id(tool_call)):
                    tool_name = _tool_call_name(tool_call)
                    tool_calls_by_id[tool_id] = {"tool_name": tool_name, "tool_input": _tool_call_input(tool_call)}
    return tool_calls_by_id, completed_tool_ids, skipped_tool_ids


class TranscriptMixin:
    """Methods of ``OpenVikingMemoryProvider`` moved here unchanged; mixed into that class."""

    def _sender_peer(self, author_id: Any) -> str:
        sender = str(author_id or "").strip()
        if sender and sender in {self._gateway_user_id, self._gateway_user_id_alt}:
            sender = self._gateway_user_id_alt or sender
        return _gateway_peer_id(self._gateway_platform, sender)

    def _current_sender_peer(self) -> str:
        current = self._turn_peer.get()
        return self._user_id if current is None else current

    @staticmethod
    def _extract_current_turn_messages(messages: Optional[List[Dict[str, Any]]], user_content: str, assistant_content: str) -> List[Dict[str, Any]]:
        """Slice the completed turn out of Hermes' full canonical transcript: the last
        assistant message matching assistant_content (else the last assistant message,
        else the transcript end) back to the matching (else nearest) user message."""
        if not messages:
            return []
        last = len(messages) - 1

        def locate(role: str, start: int, expected: Any) -> Optional[int]:
            matched = _rfind_message(messages, role, start, expected) if _message_text(expected).strip() else None
            return matched if matched is not None else _rfind_message(messages, role, start)

        end_idx = locate("assistant", last, assistant_content)
        end_idx = last if end_idx is None else end_idx
        start_idx = locate("user", end_idx, user_content)
        if start_idx is None:
            return []
        return [message for message in messages[start_idx : end_idx + 1] if isinstance(message, dict)]

    @staticmethod
    def _messages_to_openviking_batch(messages: List[Dict[str, Any]], *, assistant_peer_id: str = "", user_peer_id: str = "") -> List[Dict[str, Any]]:
        """Convert Hermes canonical messages into OpenViking batch payloads.

        OpenViking recall-tool calls/results are kept so the server can attribute
        memory usage; tool results are grouped into assistant messages; a tool call
        whose result is in the slice is emitted only via its result part.
        """
        assistant_peer_id = str(assistant_peer_id or "").strip()
        user_peer_id = str(user_peer_id or "").strip()
        dict_messages = [m for m in messages if isinstance(m, dict)]
        tool_calls_by_id, completed_tool_ids, skipped_tool_ids = _index_tool_calls(dict_messages)
        payload_messages: List[Dict[str, Any]] = []
        pending_tool_parts: List[Dict[str, Any]] = []

        def emit(role: str, parts: List[Dict[str, Any]]) -> None:
            peer_id = assistant_peer_id if role == "assistant" else user_peer_id if role == "user" else ""
            peer = {"peer_id": peer_id} if peer_id else {}
            payload_messages.append({"role": role, "parts": parts, **peer})

        def flush_tool_parts() -> None:
            nonlocal pending_tool_parts
            if pending_tool_parts:
                emit("assistant", pending_tool_parts)
                pending_tool_parts = []

        for message in dict_messages:
            role = str(message.get("role") or "")
            if role == "tool":
                tool_id = str(message.get("tool_call_id") or message.get("id") or "")
                prior_call = tool_calls_by_id.get(tool_id, {})
                tool_name = str(message.get("name") or prior_call.get("tool_name") or "")
                if tool_id not in skipped_tool_ids:
                    pending_tool_parts.append(_tool_part(tool_id, tool_name, prior_call.get("tool_input", {}), _tool_result_status(message),
                                                         tool_output=_message_text(message.get("content"))))
                continue
            if role not in {"user", "assistant"}:
                continue
            flush_tool_parts()
            text = _message_text(message.get("content"))
            parts: List[Dict[str, Any]] = [{"type": "text", "text": text}] if text else []
            if role == "assistant":
                for tool_call in message.get("tool_calls") or []:
                    if not isinstance(tool_call, dict):
                        continue
                    tool_id, tool_name = _tool_call_id(tool_call), _tool_call_name(tool_call)
                    if tool_id in skipped_tool_ids or tool_id in completed_tool_ids:
                        continue
                    # Pre-scan caches non-empty ids; parse again for the uncached empty-id case.
                    tool_input = tool_calls_by_id[tool_id]["tool_input"] if tool_id in tool_calls_by_id else _tool_call_input(tool_call)
                    parts.append(_tool_part(tool_id, tool_name, tool_input, "pending"))
            if parts:
                emit(role, parts)

        flush_tool_parts()
        return payload_messages
